### ISSUE TITLE
カメラの同期他

### ISSUE THREAD

**Issue by m-sigepon** [unity3d-jp/MeshSync#1]
・メタセコのカメラの同期のオンオフ
・頂点カラー対応
・Unity側からメタセコにインポートされる際にMat1...となるのを元のマテリアル名を適用

カメラの同期がないので、メタセコで編集されている箇所を確認するために毎回Unityでカメラを回転しないといけないので…。
適応するカメラはMain Cameraとかピックして指定できたらいいですね。
勿論カメラにアニメがある場合もあるので、オンオフ出来る形で

とても便利なので、上記対応して頂けると幸いです。

**Comment by i-saint** [comment]
フィードバックありがとうございます。
いずれも対応はそれほど難しくないはずなので、近い先に対応します。

**Comment by m-sigepon** [comment]
ご返答ありがとうございます。
よろしくお願い致します！

**Comment by i-saint** [comment]
上記 3 点対応したバージョンをリリースしました。パッケージが更新されています。

メタセコ側で "頂点カラー" がチェックされたマテリアルがどこかしらアサインされているオブジェクトは頂点カラーが同期されるようになっています。 これに該当しないオブジェクトは従来通り頂点カラーは同期されません。(色々負担が増えるので…)
.unitypackage には頂点カラー確認用のマテリアルが追加されています。また、Unity -> メタセコ へも頂点カラー持ってこれるようになっています。

カメラについては "Sync Camera" というチェックボックスが追加されているので、それを on すれば同期されます。
現状とりあえず Unity 側の Main Camera に位置を同期するようになっています。

**Comment by m-sigepon** [comment]
早い対応ありがとうございます！！
すみません頂点カラーの使用目的を先にお伝えしておけばよかったのですが、
頂点カラーの使用目的が、Unity側で作成したシェーダーでアウトラインの押し出し量調整という形で使用していまして（色を付ける目的ではなく）
メタセコ側でモデリングしてる際は、頂点カラーのチェックがオンだと見づらい（真っ黒になる）のでチェックはオフにしているのです…。
その為、頂点カラーの出力の可否はメタセコのプラグインのダイアログの方で制御できるように対応出来ないでしょうか。
（🔳Sync VertexColor　のような感じで）

ご検討よろしくお願いします。

**Comment by i-saint** [comment]
なるほど。では提案通りの方式に変更します。

**Comment by m-sigepon** [comment]
申し訳ないです、ありがとうございます！

**Comment by m-sigepon** [comment]
迅速な対応ありがとうございます！
さっそく確認致しました。
カメラの同期、頂点カラーバッチリです！
リアルタイムで頂点カラーによるアウトライン押し出し量制御が確認できて素晴らしいです！！
カメラの同期のお陰でモデリングしている箇所も同じ構図で確認できとても便利になりました。
マテリアル名の方も、対応していただいたおかげで付け直さなくて済むように成りました。

**Comment by i-saint** [comment]
よかったです！また何か問題があればできるだけ対応いたします。
あとは Maya 版が現在既にそれなりに動いていて、近い先にリリースする予定です。

**Comment by m-sigepon** [comment]
使用してみた動画を掲載してみました。
https://twitter.com/m_sigepon/status/839814981809930240

**Comment by i-saint** [comment]
awesome!
