### ISSUE TITLE
(Blender) broken UV issue

### ISSUE THREAD

**Issue by miyakou1982** [unity3d-jp/MeshSync#10]
## 内容
Blenderから吐き出したobjのUVが壊れる。
テクスチャがちゃんと貼れない。

UVs exported from blender are broken.
Can't set texture properly.

## 環境
windows 10 64bit 1709
Unity 2018.1.f2
Blender2.7.9b
MeshSync 20180514

## 再現手順
1. Cubeをsmart UVで展開
2. 適当なテクスチャを貼る
3. Auto SyncかManual SyncでUnityへ
4. Unityでテクスチャを貼る

または、Unity上でUVの状態を確認
以下の方法で確認しました。
[http://esprog.hatenablog.com/entry/2016/09/30/165057](url)

上記の方法で確認したUnity上でのUVの状態。
![15](https://user-images.githubusercontent.com/548491/40029964-73013b50-5822-11e8-9713-f432faae6e51.png)

blender上でのUVの状態
![14](https://user-images.githubusercontent.com/548491/40029870-e8ee8508-5821-11e8-8c52-41aae033026a.png)

## 解決方法
何度かblender上で２つ目のUVを作成してUnity上にもっていたときに、
うまくテクスチャ貼れたことがありますが、再現性がなかったです。

**Comment by i-saint** [comment]
フィードバックありがとうございます。
こちらも修正できたので次のリリースに反映される見込みです。

Edit Mode 時以外はほぼ UV 壊れていました。切腹モノのミスですな…。

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/MeshSync/releases/tag/20180529
