### ISSUE TITLE
Transfer user data?

### ISSUE THREAD

**Issue by crogersarvr** [unity3d-jp/MeshSync#100]
Is it possible to transfer user data from maya/DCC to unity with meshsync? for example a custom attribute in maya?  Another useful thing would be a user defined callback in unity to apply these custom attribute values to custom components on gameObjects.

**Comment by i-saint** [comment]
there is no way to handle custom attributes for now. I will check if we can support it.
on the other hand, there are already callbacks to hook scene/asset/entity updates. see [SceneEventHandler.cs](https://github.com/unity3d-jp/MeshSync/blob/20190423/.MeshSync/Assets/Tests/Scripts/SceneEventHandler.cs).
