### ISSUE TITLE
folderServerSettings bug

### ISSUE THREAD

**Issue by crogersarvr** [unity3d-jp/MeshSync#107]
Assets\UTJ\MeshSync\Editor\MeshSyncServerEditor.cs(51,61): error CS1061: 'MeshSyncServer' does not contain a definition for 'foldServerSettings' and no accessible extension method 'foldServerSettings' accepting a first argument of type 'MeshSyncServer' could be found (are you missing a using directive or an assembly reference?)

commenting out those lines fixes it.

**Comment by i-saint** [comment]
I made a new project, import MeshSync.unitypackage and it worked without any problem.
can you delete UTJ/MeshSync and reimport package? if it doesn't work, can you send me Editor.log? (https://docs.unity3d.com/Manual/LogFiles.html)

**Comment by crogersarvr** [comment]
I did not have this problem with a new project.
Thanks!

**Comment by MONKATRON** [comment]
I have the same issue - Assets\UTJ\MeshSync\Editor\MeshSyncServerEditor.cs(51,15): error CS1061: 'MeshSyncServer' does not contain a definition for 'foldServerSettings' and no accessible extension method 'foldServerSettings' accepting a first argument of type 'MeshSyncServer' could be found (are you missing a using directive or an assembly reference?)

**Comment by TanJeremy** [comment]
Hi, I found that this issue appear if the **Platform** in the **Build Settings** is setted in some **Other Platform** than **PC, Mac, Linux Standalone** : **Android** in my case.

Tested on **Unity 2019.3.5f1**
with version  **0.2.2-preview**, **0.2.3-preview**, **0.2.4-preview**

**Comment by sindharta** [comment]
Thank you for your report.
Reopening this issue.

**Comment by sindharta** [comment]
Fixed in version 0.2.5-preview.
Please let me know if you still have this problem.

**Comment by TanJeremy** [comment]
Thanks, it's working
