### ISSUE TITLE
(Blender) Object parented with empty not working correctly in Unity

### ISSUE THREAD

**Issue by miyakou1982** [unity3d-jp/MeshSync#11]
## 内容
Blender上でEmptyを親としたobjectがUnity上で位置がおかしくなり、Blender上で位置を変更しても同期しなくなる。
EmptyではないObjectを親にした場合は問題なくUnity上にもってこれてます。

Object parented with empty is not working  correctly in unity. Breaks sync with unity and not shown in correct position in unity.

## 再現手順
1. blender上でemptyを作成し、適当なobjectとparent設定(ctrl-p)
2. Unityと同期させる。

## 解決方法　Solution
親にEmptyをつかわない。

Don't use empty as parent.

**Comment by i-saint** [comment]
フィードバックありがとうございます。
問題を再現でき、手元で修正もできました。次のリリースに入る見込みです。

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/MeshSync/releases/tag/20180529
