### ISSUE TITLE
BlenderでShapeKeyを変更してもUnityに反映されません。

### ISSUE THREAD

**Issue by Agig120** [unity3d-jp/MeshSync#112]
失礼します。

動作環境 : Unity 2019.2.9f1
Blender 2.80

上記の環境ですとShapeKeyの反映が正しく行われないようです。
例)
1.Blenderで単一ボーンをつけただけの立方体を用意します。
2.適当にBase以外の ShapeKey を作って変形します。(Keyの名前をKey1とします。)
3.Unity側に MeshSync します。この際 BakeModifiers はしません。
4.Unityで Key1 の変形が正しく反映されてるのを確認します。
5.Blender側に戻り、Key1 の形状を変更してUnity側に MeshSync します。
6.Unity において変更が反映されていないのが確認できます。

Blender2.79 を使用していた時は正しく反映されていたのですが、更新してから反映されなくなりました。
こちらご調査お願いできますでしょうか？
よろしくお願いいたします。

**Comment by sindharta** [comment]
再現するために、簡単なUnity プロジェクトと Blenderのファイルを添付していただくことは可能でしょうか？

**Comment by sindharta** [comment]
Issue をこちらに移動しました。
https://github.com/Unity-Technologies/MeshSyncDCCPlugin/issues/5
