### ISSUE TITLE
About installation of Blender.

### ISSUE THREAD

**Issue by ab1ab** [unity3d-jp/MeshSync#134]
Even if 20190902.zip in MeshSync is put in Blender, it doesn't react.

When unity_mesh_sync.py among 2.8 folders of Plugin~/MeshSyncClientBlender/python/ is put in, it's transcribed in an add-on, but an error can't go out and use it.

![2020-03-03_08h18_48](https://user-images.githubusercontent.com/61766224/75836594-bbfd2b80-5e05-11ea-9cc0-320c3deba9e6.png)

![2020-03-03_08h20_04](https://user-images.githubusercontent.com/61766224/75836581-aee03c80-5e05-11ea-89ef-002a7dbb5ddf.png)

Please tell me which of which file to put in an add-on file of Blender.

**Comment by sindharta** [comment]
Issue transferred to https://github.com/Unity-Technologies/MeshSyncDCCPlugin/issues/4.

**Comment by sindharta** [comment]
@ab1ab I transferred the issue to Unity-Technologies/MeshSyncDCCPlugin#4.

On that new link, can you  please let us know which version of Blender you are using ?

上のリンクで、どのバージョンの Blender を使っているかを教えていただけますか？

**Comment by ab1ab** [comment]
v2.80.75

**Comment by sindharta** [comment]
You need to install it using a file named: `blender-2.80.zip` inside `UnityMeshSync_Blender_Windows` if you are using Windows

Do you have that file ? 
I am currently organizing the repo, and will re-upload that file soon, if you don't have it.

**Comment by ab1ab** [comment]
Do not have.
Please upload the file again.

**Comment by sindharta** [comment]
@ab1ab 
I have uploaded the previous Blender plugins here:
https://github.com/Unity-Technologies/MeshSyncDCCPlugin/releases/tag/legacy

**Comment by ab1ab** [comment]
Downloaded and introduced add-ons.
No error was displayed.
Thank you very much.
