### ISSUE TITLE
UnityInstallationProblems

### ISSUE THREAD

**Issue by AndreyZhukov** [unity3d-jp/MeshSync#170]
First I tried to install on Unity 2018.4.15f1 through adding a package from Package manager and MeshSync did appear on a list of Packages there and also under the Packages in the project, but MeshSync submenu didn't appear in the Game Object menu, neither it did in the Create menu in the scene's hierarchy panel. 
![MeshSync_PackagesManager](https://user-images.githubusercontent.com/10299367/81821027-aefd6680-9531-11ea-8068-55b738045861.png)
![MeshSync_Project](https://user-images.githubusercontent.com/10299367/81821044-b58bde00-9531-11ea-9915-f7ac3ded9bf7.png)
Turned out the problem was in the Unity version.

Then I tried to "install" it by copying MeshSync package into a folder under the "Packages" folder (embedding the package) and changed the package.json under Packages/com.unity.meshsync so there's  "unity": "2018", also tried "unity": "2018.4", but none of these two options helped in bringing the MeshSync submenu in the locations described earlier.
![package_manifest](https://user-images.githubusercontent.com/10299367/81821320-01d71e00-9532-11ea-992b-405f551114f4.png)
![package_location](https://user-images.githubusercontent.com/10299367/81821329-04397800-9532-11ea-9e83-676ff1c0bd7a.png)
![MeshSync_Embedded_Errors](https://user-images.githubusercontent.com/10299367/81821338-069bd200-9532-11ea-985e-d7092b9ba666.png)

I  guess there are some code files missing?

**Comment by sindharta** [comment]
My bad. It seems that embedding a package is only supported starting from Unity 2019.

Another thing that you can try is just copying the whole MeshSync folder into a folder under Assets.

**Comment by AndreyZhukov** [comment]
Unfortunately, still doesn't work.
Displays similar errors, but more of them:
![image](https://user-images.githubusercontent.com/10299367/81873341-e3961000-957b-11ea-9beb-20b811c25c22.png)

Before this step I've had also tried to add the line in manifest.json in the "Packages" folder:
![image](https://user-images.githubusercontent.com/10299367/81873473-21933400-957c-11ea-8aee-55df23441acc.png)
![image](https://user-images.githubusercontent.com/10299367/81873538-425b8980-957c-11ea-88ca-d8c6a39f22bf.png)
But that also didn't work.

**Comment by AndreyZhukov** [comment]
Ok, I tried this:
In Unity I imported the MeshSync.unitypackage (old version). MeshSync submenu appeared.
![image](https://user-images.githubusercontent.com/10299367/81875310-48536980-9580-11ea-8a05-2f692b06c3c5.png)
I created the server object.
![image](https://user-images.githubusercontent.com/10299367/81875336-5903df80-9580-11ea-9f08-d909d5eddf51.png)
I opened the http://127.0.0.1:8080/ in Chrome browser
![image](https://user-images.githubusercontent.com/10299367/81875435-8b154180-9580-11ea-99b3-2ce58a01cfa3.png)
andif i write some message there it is "seen"/"heard" in the Unity Console:
![image](https://user-images.githubusercontent.com/10299367/81875492-ac762d80-9580-11ea-8478-d55bfdd4a63b.png)
But when i try to export/sync from Maya (2019), I get this error:
// Error: MeshSync: Server not available. Version doesn't match server. [127.0.0.1:8080] //
![image](https://user-images.githubusercontent.com/10299367/81875606-eb0be800-9580-11ea-927f-20c1936db6eb.png)
so as if Maya didn't "see" the server (even though Unity has no problem "seeing" it).
So I'm wondering now, has server "address" changed in the new version of MeshSync? Wasn't it 127.0.0.1 in the times of .unitypackage? If so, where can I change it for Maya?
🤔

**Comment by sindharta** [comment]
> So I'm wondering now, has server "address" changed in the new version of MeshSync? Wasn't it 127.0.0.1 in the times of .unitypackage? If so, where can I change it for Maya?

No, it hasn't changed. 127.0.0.1 always points to the local computer.
What I can think of, is that the MeshSync (Unity) version on your computer does not match the MeshSync plugin version on Maya.

I just tried creating a test project using Unity 2018 with MeshSync, and as you said, there were a lot of compile errors. I removed the functionalities that require Unity 2019, and here is the project: [Test2018.4.22_MeshSync.zip](https://github.com/unity3d-jp/MeshSync/files/4625791/Test2018.4.22_MeshSync.zip)

This should work with [0.1.0-preview DCC plugins](https://github.com/Unity-Technologies/MeshSyncDCCPlugins/releases/tag/0.1.0-preview).

Another alternative if you must use the old unitypackage version, is first to check if you have [the latest unitypackage we released](https://github.com/unity3d-jp/MeshSync/releases/download/20190902/MeshSync.unitypackage
) and use [the legacy DCC plugins](https://github.com/Unity-Technologies/MeshSyncDCCPlugins/releases/tag/legacy).

**Comment by AndreyZhukov** [comment]
Genius! Thank you so much it works! I opened your test project and it works there with both Blender and Maya (after some rearrangements with the plugin there). I'm so happy it works! :D And excited!
Haven't tested the alternative, but I probably will.
Ok, time for experiments! :D
Thank you! <3

**Comment by sindharta** [comment]
Glad to hear it :D
