### ISSUE TITLE
メタセコイア４から出力するとすべてのマテリアル名が空白

### ISSUE THREAD

**Issue by devil-tamachan** [unity3d-jp/MeshSync#18]
メタセコイア４から出力するとすべてのマテリアル名が空白になります

**Comment by i-saint** [comment]
情報ありがとうございます。再現取れました。
単純なケアレスミスにより Release 20180529 で混入したバグのようです…。次のリリースで直しておきます。

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/MeshSync/releases/tag/20180918
