### ISSUE TITLE
More DCC Tools support

### ISSUE THREAD

**Issue by i-saint** [unity3d-jp/MeshSync#22]
### Possibly be done in the future
- [ ] Houdini
- [ ] Cinema 4D
- [ ] Photoshop (texture and screen painting)

### Done
- [x] Modo
- [x] VRED
- [x] Motion Builder
- [x] 3ds Max
- [x] Maya
- [x] Blender
- [x] xismo
- [x] Metasequoia

### Gave up
- [x] ZBrush
  - no plugin API and it's software rendering (= impossible to snoop vertices)

**Comment by sindharta** [comment]
Transferred to https://github.com/Unity-Technologies/MeshSyncDCCPlugin/issues/7
