### ISSUE TITLE
Blender: Mirror Modifier with Mirror Object Support

### ISSUE THREAD

**Issue by AndreyZhukov** [unity3d-jp/MeshSync#27]
Hi,

First I thought that Mirror modifier doesn't work at all, but it turned out it works only along it's true pivot point, not when a Mirror Object is specified: then it just ignores it and mirrors using it's own pivot.

Also if it's possible, please make an option in Blender addon "Apply Modifiers", which will, like in FBX export, apply all the modifiers before exporting (here syncing). :)

Best wishes,
Andrey

**Comment by i-saint** [comment]
thanks for valuable feedbacks.

> Mirror modifier

understood. I will try to fix it. 


> "Apply Modifiers" option

it is certainly possible. actually, I once made this option when developing, but removed eventually because it is problematic.
- too slow. no one wants to use it with "Auto Sync".
- skinning will be baked inevitably. almost all cases this should be undesirable.

**Comment by AndreyZhukov** [comment]
> too slow. no one wants to use it with "Auto Sync".

You could add a warning icon and/or warning pop-up with confirmation that one understands the risk of using this option (and maybe put it under some roll-out to even more prevent accidental clicks).

> skinning will be baked inevitably. almost all cases this should be undesirable.

Is it possible to add an exception for ArmatureModifier?

**Comment by i-saint** [comment]
> Is it possible to add an exception for ArmatureModifier?
it is far difficult than bake-everything. I don't think it is worth to effort.

**Comment by i-saint** [comment]
I just realized it is not difficult. it is just impossible.
anyway, I won't revive "Apply Modifiers" mode unless there is any good reason. I treat this issue as just a bug about Mirror Modifier support.

**Comment by AndreyZhukov** [comment]
Ok, I see :)
Yeah, sure, no problem :)

**Comment by AndreyZhukov** [comment]
Hi,

I'm not sure if this is the right place to write an email, or will it reach
you, but I haven't found another email address, so...
Could you please tell me how to install the latest version of MeshSync on
the Unity side? I have managed to install it on Maya, but haven't found
instructions for Unity. Previously there was just a MeshSync.unitypackage,
and now there isn't, I tried many things and haven't succeeded yet, so I
ask you to help me with that, maybe a link to instructions?

Thank you in advance!

Kind regards and stay safe,
Andrey

**Comment by sindharta** [comment]
Hi, you can always create a new issue for asking.

We have moved from unitypackage format to a package that you can find inside the Package Manager. You can find the package now from the Package Manager (remember to check the "Show preview packages" checkbox)
![image](https://user-images.githubusercontent.com/7379311/81762043-9166d780-9506-11ea-90d7-edf124679cac.png)

The DCC plugins themselves have been moved to another repository, and this is the i[nstallation instruction](https://github.com/Unity-Technologies/MeshSyncDCCPlugins/blob/dev/Plugins~/Docs/en/Installation.md).

**Comment by AndreyZhukov** [comment]
Wow! Thank you so much for your prompt response! I spent roughly the whole
evening yesterday figuring this out :) And it obviously turned out to be
that easy! :)) Please add this also to the main page.

Thank you again <3
Kind regards,
Andrey

**Comment by AndreyZhukov** [comment]
Hi again :) Sorry.. I did install it through the packages (Package
Manager), it showed up there, in the list of packages, and in the project
folders, but unfortunately there's no MeshSync menu in the GameObject menu,
nor under the "Create" (in the Scene). Do you know what could be
the problem? Is it the Unity version? I'm using 2018.4.15f1
[image: image.png]
[image: image.png]

Thank you again in advance!
Andrey

**Comment by sindharta** [comment]
Yes, it's the Unity version. 
The package is made for Unity 2019.3 or above.

Is it possible for you to upgrade your Unity version ?

**Comment by AndreyZhukov** [comment]
Oh :( Ok
Now I'm afraid there isn't, later for sure.
Is there maybe a version of MeshSync for older versions of Unity?

**Comment by sindharta** [comment]
I am afraid not.

You can try to "hack" it by copying MeshSync package into a folder under the "Packages" folder. This is for setting it up as an embedded package.
https://docs.unity3d.com/Manual/CustomPackages.html#EmbedMe

Then, you need to change package.json under Packages¥com.unity.meshsync so that it supports Unity 2018, and fix any compile error if there is any

**Comment by AndreyZhukov** [comment]
Ok, thank you, I'll try this.

**Comment by AndreyZhukov** [comment]
I did that
[image: image.png]
[image: image.png]
but some errors appear and still there's no MeshSync Options in GameObject
and Create :/
[image: image.png]
I created a new project to embed the package.

**Comment by AndreyZhukov** [comment]
Tried also *"unity": "2018.4",* also doesn't work.

**Comment by sindharta** [comment]
Can you create a new issue and repost your images ?
I can't see them here.

**Comment by AndreyZhukov** [comment]
Oh, yeah, sure.

**Comment by AndreyZhukov** [comment]
https://github.com/unity3d-jp/MeshSync/issues/170
