### ISSUE TITLE
Blender: Sync animation without backing (as is)

### ISSUE THREAD

**Issue by AndreyZhukov** [unity3d-jp/MeshSync#28]
Hi,

Is it possible to export animation as is, without backing it every N'th frame? Sometimes animations are quite simple and there's no need to bake them, for baking makes a lot of keys. It would be nice to disable baking by e.g. setting Frame Step to 0. I tried this but it usually just crashes Blender.
I understand that if one uses weighted tangents in Blender it could be supported only with the latest versions of Unity (from 2018 I guess), cause earlier versions didn't have weighted tangents support.

**Comment by i-saint** [comment]
I tried it but gave up. this is not just a weighted tangents problem. there are several difficulties, but the most serious one is constraints. I need to implement every possible Blender's constraints (includes plugins/add-ons) in Unity to make this happen, which is definitely impossible.

> setting Frame Step to 0. I tried this but it usually just crashes Blender.
oh, this is bad. I will fix it.

**Comment by AndreyZhukov** [comment]
I had in mind transferring animation without constraints, just simple animation with parenting (for simple stuff). :) But if Frame Step set to 0 will do sth similar that works for me ^_^
