### ISSUE TITLE
[Question] Support dual way communication

### ISSUE THREAD

**Issue by CRoeckhout** [unity3d-jp/MeshSync#288]
Hey thank you for your awesome job to every contributors !

I was wondering do you think we can hope to some have some kind of inverted way in the process ? like imagine we move objects inside of the MeshSyncServer gameobject and they would be added to your blender scene ?

This way we could edit the whole unity scene inside of blender. I think this would be a very valuable thing for the purpose of environment.

Thanks a lot for your answer.

**Comment by sindharta** [comment]
Unfortunately, the scope of MeshSync is to sync assets from DCC tools to Unity, and not vice versa.

For exporting from Unity to DCC tools, please refer to https://docs.unity3d.com/Packages/com.unity.formats.fbx@latest

**Comment by CRoeckhout** [comment]
Thanks a lot @sindharta :)
