### ISSUE TITLE
Second machine not syncing

### ISSUE THREAD

**Issue by nebadon2025** [unity3d-jp/MeshSync#30]
I have setup everything I think correctly, I have local machine unity and blender syncing properly, but a second machine on same network can not sync scene or load x.x.x.x:8080 in to web browser and get a response, I am using Unity 2017.2.3 is this version supported or are there any extra steps, I have opened up port on firewall on both machines and no other security software running during test and still unable to get things syncing up, any suggestions?

**Comment by i-saint** [comment]
Unity 2017.x is supported. we tested sync with dufferent machines and different OS (Linux-Blender   Windoes-Unity, etc) and confirmed it works.
I guess security software is still active and blocking access, but not sure.

**Comment by i-saint** [comment]
if you need more advice, add detailed information.
but as it is working on local, it is likely that problem is in network or security software.
