### ISSUE TITLE
Cannot install plugin for blender 2.83

### ISSUE THREAD

**Issue by mikemeyers1** [unity3d-jp/MeshSync#301]
After installing latest version package 5.5 I go into Unity preferences (Unity 2019.4) and when i hit install for blender 2.83 it says that there is an error and it has failed to install plugin. No other information. I also tried to download the file to manually install the plugin from the 5.3 release but when I tried to extract the zip file it says it is in an unknown format or corrupted.

**Comment by sindharta** [comment]
Can you please let me know:
1. The exact Blender 2.83 version. I believe we have 2.83.0 - 2.83.9 at the moment, and you should be able to verify it by looking at the splash screen when Blender starts.
2. Your OS  (Windows, Mac, Linux ?)

Also, could you please try to:
1.  delete the following folder: `Assets\MeshSyncDCCPlugins~` in your project
2.  go to Unity Preferences again to install the plugin for Blender 2.83
3. make sure that the detected path exactly points to where Blender is located.
![image](https://user-images.githubusercontent.com/7379311/101302990-5d774900-3880-11eb-9170-58b39dc15aeb.png)

If you'd like to install the plugin manually, please refer to the following page:
https://github.com/Unity-Technologies/MeshSyncDCCPlugins/blob/dev/Documentation~/en/Installation.md

`0.5.3-preview` was a release candidate, but had bugs and has been superseded by the later version.

Currently, the latest versions for both packages are:
1. `0.5.5-preview` for MeshSync
2. `0.5.4-preview` for MeshSyncDCCPlugins

**Comment by mikemeyers1** [comment]
Blender 2.83.0, using Windows, I resolved by installing the plugin designated for 0.54

**Comment by sindharta** [comment]
Glad to hear that.
Closing this issue now. Please let me know if you have any problem.
