### ISSUE TITLE
RizomUV pipeline ??

### ISSUE THREAD

**Issue by davoodkharmanzar** [unity3d-jp/MeshSync#338]
it would be great if be able to transfer selected scene object mesh from unity to [RizomUV  ](https://www.rizom-lab.com/rizomuv-vs/) to build primary uv or lightmapping uv  :]

something like as RizomUV [bridges ](https://www.rizom-lab.com/bridges/)...

thanks a lot.

**Comment by sindharta** [comment]
Closing due to being duplicate with 
https://github.com/Unity-Technologies/MeshSyncDCCPlugins/issues/97
