### ISSUE TITLE
Cant get motionbuilder 2019/2018 to work with Meshsync

### ISSUE THREAD

**Issue by Hermanator123** [unity3d-jp/MeshSync#345]
Hi Unity.
Im trying out Meshsync, creating an AR application with normcore sdk and meshsync.
It works great with blender but I need it to work with Motionbuilder .

Im having issues not being able to connect motionbuilder to Unity.
Plugin is offline in motionbuilder see picture1.
The motiobuilder plugin is not showing up in unity Preferences.

Any ideas how to fix?

![Meshsync1](https://user-images.githubusercontent.com/37322452/116203697-41dfe280-a73c-11eb-8e60-e8e13c2dbb6b.jpg)
![Meshsync2](https://user-images.githubusercontent.com/37322452/116203713-44dad300-a73c-11eb-9d05-d9900ac116a0.JPG)

Best regards
Herman

**Comment by sindharta** [comment]
Duplicate with https://github.com/Unity-Technologies/MeshSyncDCCPlugins/issues/107
Closing.
