### ISSUE TITLE
blender crashes when enabling auto sync

### ISSUE THREAD

**Issue by kromar** [unity3d-jp/MeshSync#346]
when i enable auto sync blender crashes. This is found in the crash log. Please let me know if you need any more information since its unclear to me what causes this issue.

# Python backtrace
  File "C:\Repo\BlenderAddonDevelopment\development\src_28\addons_contrib\unity_mesh_sync_common.py", line 62 in msb_on_toggle_auto_sync
  File "C:\Repo\BlenderAddonDevelopment\development\src_28\addons_contrib\unity_mesh_sync.py", line 116 in invoke

**Comment by sindharta** [comment]
So, considering one of your other posts here:
https://github.com/unity3d-jp/MeshSync/issues/339#issuecomment-845506246

I assume you somewhat managed to find a way to install MeshSyncDCCPlugin for Blender 2.92 ?
If that is the case, then, like I mentioned in the above thread, we don't support Blender 2.92 yet, so the behavior will be undefined (it may work/crash).

**Comment by kromar** [comment]
i got it working with older blender versions so closing this issue
