### ISSUE TITLE
mesh does not sync from unity to blender

### ISSUE THREAD

**Issue by kromar** [unity3d-jp/MeshSync#349]
when i duplicate or add a object in unity i would expect the mesh to by sent over to blender but i can not get that to work.
im not sure if that is by design a limitation or another issue im running in to. 
If it is by design, is it planned to add the functionality to sync a object in both directions and not just from blender to unity?

**Comment by sindharta** [comment]
MeshSync is designed to sync only one way from the DCC tool to Unity.

To export objects from Unity to DCC tools, we can use [FBXExporter](https://docs.unity3d.com/Packages/com.unity.formats.fbx@latest), although, yes, there is no "sync" process like what MeshSync provides.

**Comment by kromar** [comment]
thats to bad, i was looking for such a functionality. do you have any plans to implement that in the future?

**Comment by sindharta** [comment]
Unfortunately, this is not in our roadmap at the moment.

**Comment by sindharta** [comment]
Closing this issue due to above reason
