### ISSUE TITLE
pivot issue

### ISSUE THREAD

**Issue by 3dxiaofeng** [unity3d-jp/MeshSync#35]
Hi ,i'm a max and maya user. Your great tool is quite valuable for setup a bridge between DCC and unity.
But if I modify the pivot in both MAX and Maya, the plugin will sync the movement onto the mesh itself instead of its pivot. Now my workaround is to link the mesh on another one which is put to a location of the new pivot i want. Is it an issue or I missed something? Many thanks.

**Comment by i-saint** [comment]
thanks for the report.
I cared nothing about pivot points so far. and I just realized this is not an easy issue to solve. I will work on it, but maybe fix won't come soon.

**Comment by 3dxiaofeng** [comment]
WOW! Thanks for ur talent work!

**Comment by i-saint** [comment]
fixed Maya issue in the latest release.
