### ISSUE TITLE
mayaとunityでの同期で一部のオブジェクトが同期されない

### ISSUE THREAD

**Issue by kazukiHiromori** [unity3d-jp/MeshSync#350]
質問です。  
maya上でRigidBodyを使用しシュミレーションをかけたシーンを同期しようとした際に、unity側に反映されずそもそもオブジェクトがunityのシーンに配置されません。上記のシーンデータをFBXデータとしてMayaから書き出し、MayaでFBXデータとして読み込んだ際にはきちんと同期は行われていました。  
同期を行う際に同期出来る条件などはあるのでしょうか？条件などがあればご教授お願いします。

**Comment by sindharta** [comment]
確認したいと思いますので、そのデータを頂くことは可能でしょうか？
また、問題となる場面の画像や録画などを添付して頂ければ幸いです。
どうぞよろしくお願いいたします。

**Comment by sindharta** [comment]
返事がなかったので、一旦 issue をクローズします。
何かあれば、この issue を再開してください。
