### ISSUE TITLE
Does MeshSync support export multi uvs from maya to unity?

### ISSUE THREAD

**Issue by Alunice** [unity3d-jp/MeshSync#384]
I have a model with 2 uv channels in maya, but in unity,I find that the mesh has only one uv channel be imported.

I read the MeshSyncPlayer.cs code and notice that contains HasUV function,but debug shows only uv0 is true.

I don't know what I did wrong or just MeshSync does not support multi uvs in maya.

THX~

**Comment by sindharta** [comment]
MeshSyncDCCPlugin doesn't support multi uvs for Maya yet, as can be seen from its [documentation](https://github.com/Unity-Technologies/MeshSyncDCCPlugins).

**Comment by Alunice** [comment]
> MeshSyncDCCPlugin doesn't support multi uvs for Maya yet, as can be seen from its [documentation](https://github.com/Unity-Technologies/MeshSyncDCCPlugins).

thx~

**Comment by sindharta** [comment]
No problem. Closing this issue now.
