### ISSUE TITLE
Could not reach server (timeout)

### ISSUE THREAD

**Issue by Alunice** [unity3d-jp/MeshSync#385]
I got this error in maya sometime(not usually).
![timeout](https://user-images.githubusercontent.com/20534350/128706560-eda55b62-8705-4151-b40a-0d73fbf5e852.png)

but in unity, meshsync server has started......

![meshsyncserver](https://user-images.githubusercontent.com/20534350/128706707-2fe36f74-7654-4fe2-a646-c1ded7f39ab9.png)

reopen the unity or maya seems helpless, how can i fix this?

**Comment by sindharta** [comment]
So, two suggestions:
1. Try changing the port number in both Unity and DCC tool side to something else.
2. Disable all firewall that you may have installed temporarily, and see if the connection works.

Also, make sure you only have a single Unity instance with one MeshSyncServer GameObject

**Comment by Alunice** [comment]
> So, two suggestions:
> 
> 1. Try changing the port number in both Unity and DCC tool side to something else.
> 2. Disable all firewall that you may have installed temporarily, and see if the connection works.
> 
> Also, make sure you only have a single Unity instance with one MeshSyncServer GameObject

THX,I fix that problem by restart my computer,mabye there are some environment conflict or port occupation？I will try your suggestions next time if I met the problem again.Thanks for your answer!

**Comment by sindharta** [comment]
You're welcome.
I am closing this issue now. 
Please feel free to reopen if the issue persists.
