### ISSUE TITLE
animation Syncについてjoint animationを認識する場合としない場合があるようです

### ISSUE THREAD

**Issue by TsuPMC** [unity3d-jp/MeshSync#42]
テスト環境
Unity2018.2.9f1/MeshSync-master180918/Maya2017Update5

animation Syncについて
Mayaでjointにコントローラーを付けてanimationさせ、Unityに転送した場合、正しくanimationが再現される場合とそうでない場合があります
jointにanimationをbakeすると正しく転送されるのですがそれだと不便というかUnityで手軽にpreview確認ができるイメージではなくなります
コントローラーはjointにコンストレインで接続されているだけです

**Comment by i-saint** [comment]
情報ありがとうございます。
お手数ですが、問題再現できるシーンを添付してもらえますでしょうか。再現さえできれば単純な内容で大丈夫です。

**Comment by TsuPMC** [comment]
単純な内容だと再現できなかったので人型データをお送りさせていただくことになります
こちらのページだとはばかれますので別途メールでお送りさせていただきます
どうぞよろしくお願いいたします

**Comment by TsuPMC** [comment]
承知いたしました
Sync機能は正直とても欲しいので解決できるととてもありがたいです
どうぞよろしくお願いいたします

**Comment by i-saint** [comment]
幸い原因は思っていたよりも単純なところにあり、修正は難しくありませんでした。
こちらの Maya プラグインであれは問題は起きないはずです。お手数おかけいたしますが、試していただけると幸いです。(Unity 側には変更はありません)
[UnityMeshSync_Maya_Windows.zip](https://github.com/unity3d-jp/MeshSync/files/2748762/UnityMeshSync_Maya_Windows.zip)

**Comment by TsuPMC** [comment]
確認させていただきました
解消されました！
とても助かります！
どうもありがとうございました

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/MeshSync/releases/tag/20190315
