### ISSUE TITLE
要望：同名マテリアル検出とアサイン機能

### ISSUE THREAD

**Issue by TsuPMC** [unity3d-jp/MeshSync#43]
これは要望になるのでこちらに記載してもいいものかわかりませんが
マテリアルリストで検出されたのと同名のマテリアルをUnity Project内から検出して（フォルダを指定して検出とかでもいい）同名があれば自動アサインとか可能にならないでしょうか

**Comment by i-saint** [comment]
了解しました。実装も難しくないと思われます。

**Comment by TsuPMC** [comment]
ありがとうございます！

**Comment by i-saint** [comment]
実装してみました。可能であれば、意図した挙動になっているか試していただけると幸いです。Assets\UTJ\MeshSync\Runtime\Scripts\MeshSyncServer.cs を↓の中身で上書きすれば有効になります。
[MeshSyncServer.zip](https://github.com/unity3d-jp/MeshSync/files/2740651/MeshSyncServer.zip)

- MeshSyncServer に "Find Material From Assets" というチェックが追加されています (デフォルトで有効)。これが有効だとプロジェクト内から名前が合致する Material を探すようになります。
- プロジェクト内のマテリアルを使う場合、DCC 側のマテリアルのパラメータは一切反映されなくなります。反映すると事故の元になりそうなのでこうしていますが、これは要望次第で変更も可能です。

**Comment by TsuPMC** [comment]
早速ありがとうございます
MeshSyncServer.csを上書きすると下記エラーが出てHierarchyでMeshSyncServerがcreateできなくなりました

20180918版エラー
Assets/UTJ/MeshSync/Scripts/MeshSyncServer.cs(24,18): error CS0260: Missing partial modifier on declaration of type `UTJ.MeshSync.MeshSyncServer'. Another partial declaration of this type exists

20181130版エラー
Assets/UTJ/MeshSync/Scripts/MeshSyncServer.cs(2266,13): error CS0103: The name `DeployStreamingAssets' does not exist in the current context

**Comment by i-saint** [comment]
申し訳ありません、先の MeshSyncServer.cs には本件以外の変更も含まれていたのを失念しておりました。
こちらでお試しください。20181130 版を前提としています。
[MeshSyncServer.zip](https://github.com/unity3d-jp/MeshSync/files/2743302/MeshSyncServer.zip)

**Comment by TsuPMC** [comment]
もう一つご相談が…
animationを作成する際、mayaではアセットをリファレンスしていることが多いのですが、リファレンスはネームスペースを付けて名前管理をしているのが常です
https://knowledge.autodesk.com/ja/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2015/JPN/Maya/files/GUID-DD72DBEC-4B6D-4473-A4C5-CDA80DB8FAEB-htm.html
なので、添付画面のようにSyncするマテリアル名にも全てネームスペースがついてしまうのですが、:の後ろの名前で検出して自動アサインなんてできないでしょうか
:は複数ある場合もあります
その場合は文字列を左から検出して最後の:より左がネームスペースになります
![image](https://user-images.githubusercontent.com/39584741/51022102-ad7eff80-15c6-11e9-87e3-25d077a412a0.png)

![image](https://user-images.githubusercontent.com/39584741/51021580-5167ab80-15c5-11e9-8af1-0894ae228949.png)

**Comment by i-saint** [comment]
了解いたしました。Maya 側にネームスペース省略オプションを追加しようと思います。
一つ疑問があるのですが、このオプションはマテリアルだけ大丈夫でしょうか。ノード名にも適用したほうがいいでしょうか。

(アニメーションの件でもネームスペースの話がありましたが、Maya のネームスペースについて馴染みがないため、いまいち問題が把握できておらずにいます)

**Comment by TsuPMC** [comment]
＞一つ疑問があるのですが、このオプションはマテリアルだけ大丈夫でしょうか。ノード名にも適用したほうがいいでしょうか

それもお願いできますか？
それができると願ったりかなったりなのです
![image](https://user-images.githubusercontent.com/39584741/51023785-15cfe000-15cb-11e9-8167-e51d91c57331.png)

どうぞよろしくお願いいたします

**Comment by i-saint** [comment]
了解いたしました。

**Comment by i-saint** [comment]
ネームスペース除去オプションを追加いたしました。デフォルトで有効になっています。
Maya プラグイン側のみの変更になります。こちらを試していただけると幸いです。
[UnityMeshSync_Maya_Windows.zip](https://github.com/unity3d-jp/MeshSync/files/2758206/UnityMeshSync_Maya_Windows.zip)

**Comment by TsuPMC** [comment]
時間が空いてしまって申し訳ないです
これから試させていただき、またご報告させていただきますのでよろしくお願いいたします

**Comment by TsuPMC** [comment]
試させていただきました
きれいなデータ（ネームスペースが一つ）ではネームスペース除去できてました

ただ厳密なことを申しますとネームスペースが多重になっている場合があるので（これはきれいなデータではないのですが往々にしてこういうことが起こるのです）、全てのネームスペースが除去できていることが望ましいのです
![namespace001](https://user-images.githubusercontent.com/39584741/51297764-12be6f00-1a65-11e9-976f-5a10c26063c2.jpg)

「文字列を左から検出して最後の:より左がネームスペース」なのでそれを除去
みたいな処理ができませんでしょうか

ネームスペースが多重になっている場合：
●多重リファレンス（オブジェクトをリファレンスしているシーンをリファレンスしている）みたいなことをしている
●リファレンスは１回しかされてないが、以前付けたネームスペースを取り忘れている

もうずうずうしくお願いばかりしておりましてすみません
ご検討いただければ幸いです

**Comment by i-saint** [comment]
ご指摘ありがとうございます。
多重ネームスペース除去にも対応いたしました。試していただけますと幸いです。
[UnityMeshSync_Maya_Windows.zip](https://github.com/unity3d-jp/MeshSync/files/2767345/UnityMeshSync_Maya_Windows.zip)

Maya は UTJ 社内には日常的に使ってる者がおらず、本件のように私達だけでは気付けない問題が多いです。なので実際に制作現場で使っている方々からのフィードバックはとても貴重で、助かっております。

**Comment by TsuPMC** [comment]
確認させていただきました
ネームスペースが何重になっていても消せることが確認できました
お早いご対応に感謝申し上げます
どうもありがとうございました

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/MeshSync/releases/tag/20190315
