### ISSUE TITLE
ご質問：生成されたanimation clipについて

### ISSUE THREAD

**Issue by TsuPMC** [unity3d-jp/MeshSync#45]
MeshSyncで生成されたanimation clipデータについて質問があります

容量をみますと、生成されたanimation clipの容量はそのままだと随分小さいようで
![image](https://user-images.githubusercontent.com/39584741/51024272-6dbb1680-15cc-11e9-870c-0bf8c77b9df9.png)
例えばsave projectをする、とかすると容量が増えます
![image](https://user-images.githubusercontent.com/39584741/51024296-7f9cb980-15cc-11e9-8d32-b73aa9fff47b.png)

Syncしただけのデータは実体がないとかそういったものでしょうか？
Syncで生成されたanimation clipを使いまわせるといいな（FBXでDCCツールからanimationデータを書き出さなくてもそのまま本番用animation clipとして使えないかな）と思ったのですがそういった用途で使うようにはできてないですか？

テスト環境
Unity2018.2.9f1/MeshSync-master181130/Maya2017Update5

**Comment by i-saint** [comment]
現状 save project するまでメモリ上にしかデータがないようです。sync 直後にディスクへ書き出しまでやるようにしておきます。

animation clip の再利用は、Unity 上で Hierarchy の構造が一致していれば可能です。
元々シーン単位で同期することが目的 (better Alembic のようなイメージ) で、シーン間でのデータの再利用はあまり考えていませんが、現状結果的に再利用可能な形にはなっているはずです。これは要望次第ではできるだけ考慮しようと思います。

**Comment by TsuPMC** [comment]
「sync 直後にディスクへ書き出し」ご対応いただけるとのことありがとうございます

「シーン間でのデータの再利用」を試してみたいと思っています
現状他の項目でも色々要望など出させていただいてご対応いただいていることである程度「再利用」は可能なのではないかと考えています
（ある程度と断っているのは弊社独自の仕様などが絡んでくるからです）

いずれにしてもテストしていきたいです

どうぞよろしくお願いいたします

**Comment by i-saint** [comment]
なるほど。アニメーション抽出後、値に変化がない key を削除する処理を入れているんですが、これが障害になっているようです。オプションで有効/無効を切り替えられるようにして、デフォルトで無効にしておきます。

ちなみに key を削除しているのは、Unity のアニメーションのインポート処理が非常に遅く、それを少しでも軽減するためでした。
余談になりますが、複数の MotionBuilder のユーザーの方々から、アニメーションもリアルタイムに同期してほしい (= Auto Sync のアニメーション板がほしい) という要望を頂いているんですが、このインポートの遅さのせいで現状諦めざるを得ない感じになっています。

**Comment by TsuPMC** [comment]
なるほど！
「アニメーションもリアルタイムに同期してほしい (= Auto Sync のアニメーション板がほしい) という要望を頂いているんですが、このインポートの遅さのせいで現状諦めざるを得ない感じになっています」
アニメーターからはそのような要望は確かに出るでしょう…

「オプションで有効/無効を切り替えられるようにして」の処理は大変ありがたいです
「デフォルト無効」も承知いたしました　MeshSyncの本来の使い方からするとまったくそうでしょう

ご無理を申しまして申し訳ありません
ご対応いただけること大変感謝申し上げます

どうもよろしくお願い申し上げます

**Comment by i-saint** [comment]
sync 直後ディスクへ書き出し、対応いたしました。こちらは Unity 側、MeshSyncServer.cs のみの変更になります。
[MeshSyncServer.zip](https://github.com/unity3d-jp/MeshSync/files/2778808/MeshSyncServer.zip)

キーフレームリダクション有効/無効オプションも対応いたしました。こちらは Maya プラグイン側の変更になります。Animations の項目に "Keyframe Reduction" チェックが追加されています。(デフォルトで無効、と書きましたが、結局有効にしました)
[UnityMeshSync_Maya_Windows.zip](https://github.com/unity3d-jp/MeshSync/files/2778789/UnityMeshSync_Maya_Windows.zip)

また、本件とは関係は薄いですが、来週あたりに新しいバージョンをリリースする予定です。本件を含むこれまでの変更、および Maya 2019, MotionBuilder 2019 などへの対応版が含まれる予定です。

**Comment by TsuPMC** [comment]
ありがとうございます
今テストさせていただいてますのでまたご連絡させていただきます

新バージョンリリース情報もありがとうございます

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/MeshSync/releases/tag/20190315
