### ISSUE TITLE
Find Material From Assetsが一部正しくアサインされない

### ISSUE THREAD

**Issue by TsuPMC** [unity3d-jp/MeshSync#51]
お世話になっております
新機能のリリースありがとうございました
早速試させていただきましたが表題の通り一部マテリアルが自動アサインされませんでした
（#43でご対応いただいたときは問題なく同期いたしておりました）
正しく同期されるものもあります
何か細かい仕様などございますでしょうか　ご教示いただけますと助かります
画像だけではわからないようでしたらお手数ですがご連絡いただけますでしょうか
![FindName](https://user-images.githubusercontent.com/39584741/54486112-dd000000-48c6-11e9-8429-f9130b4e2061.jpg)

**Comment by i-saint** [comment]
名前が部分一致するマテリアルがある場合、正しくアサインされないことがある現象はこちらでも確認できました。(例: ahoge というマテリアルが存在する場合、maya 側では名前 hoge なのに ahoge がアサインされることがある)

お手数ですが、こちらのファイルで更新して改善されるか試していただけますでしょうか。マテリアルリストの改善 (マテリアルの名前の表示領域がフィットするように) も入っています。
[MeshSyncServer.zip](https://github.com/unity3d-jp/MeshSync/files/2994957/MeshSyncServer.zip)
MeshSyncServer.cs は Assets\UTJ\MeshSync\Runtime\Scripts に、MeshSyncServerEditor.cs は Assets\UTJ\MeshSync\Editor にあります。

提供いただいているスクリーンショットを見るに、こちらで確認した現象とは似て非なものである感じもしますが、その場合アセットを提供いただいてこちらで再現を取らないと修正は難しいかもしれません。

**Comment by TsuPMC** [comment]
テストさせていただきました
一部アサインされて一部はアサインされないという現象が出ています
テストデータをどうお送りしようか思案中です

**Comment by TsuPMC** [comment]
テストデータを作成してお送りさせていただきました
ご確認いただけますと助かります
よろしくお願いいたします
