### ISSUE TITLE
Support For Blender 3.0? 

### ISSUE THREAD

**Issue by David-Everlasting-Media** [unity3d-jp/MeshSync#514]
-I manually added both Blender 2.93 and 3.0
--2.93 installed fine. Prompt says: "Failed in installing plugin. Please make sure to close down all running instances of Blender 3.0". 
There are no running instances of Blender 3.0, and I gave the system a fresh reboot. I was running Blender from Steam at the time, so I presumed it could have been Steam interfering or keeping a passive process/service running. So, I installed the non-Steam version of Blender 3.0 and tried again, no luck.

**Comment by sindharta** [comment]
MeshSync (Or [MeshSyncDCCPlugins](https://github.com/Unity-Technologies/MeshSyncDCCPlugins) to be exact) doesn't support Blender 3.0 yet at the moment, but we are looking into it.

**Comment by sindharta** [comment]
Closing this issue as MeshSyncDCCPlugins is the appropriate place to create it.
