### ISSUE TITLE
BlendShapeについてご質問

### ISSUE THREAD

**Issue by TsuPMC** [unity3d-jp/MeshSync#53]
BlendShape　animationについて質問があります

MeshSyncでUnity内に生成されるanimation clipの中にBlendShapeのanimationカーブは確認でき、実際にMeshSync sceneではBlendShape animationが再生されました

が、このanimation clipはmayaからfbx出力したモデル（Skinned Mesh Renderer にBlendShapeは持っている）には(BlendShape animationが）再生されないのですが、仕組み上そういうものですか？

**Comment by i-saint** [comment]
AnimationCurve の名前が一致していれば再生できるはずです。(手元で再生できるのを確認しました)
ただ、名前を一致させるにはいくつか条件が必要で、
- fbx でエクスポートするオブジェクトが Maya 側でルートノード (親を持たない) であること
- fbx でエクスポートする際、ファイル名をオブジェクト名と同じにする
が必要です。
他にも見落としている条件があるかもしれません。fbx でも Blendshape のアニメーションを出力し、両者の AnimationCurve の名前の規則性を確認してみたほうがいいと思います。

namespace などが原因で一致しなくなっている可能性もありますが、この場合は再現データを送っていただけるとすぐに解決できるかもしれません。

**Comment by i-saint** [comment]
別件で恐縮ですが、pivot が fbx で持ってきたデータと一致しない問題、とりあえず手元では解決を確認できました。が、影響が大きい変更ゆえにどこか別の部分で問題が出ている可能性を否定できません。
お手数ですがそちらでも検証していただけますでしょうか。
[MeshSync_20190326_internal.zip](https://github.com/unity3d-jp/MeshSync/files/3007327/MeshSync_20190326_internal.zip)

**Comment by TsuPMC** [comment]
こちらで調査いたしましたところ、恐らくnamespaceの問題ではないかと考えています
テストデータをお送りさせていただいたのでご確認いただけますでしょうか
よろしくお願いいたします

**Comment by TsuPMC** [comment]
あ、レスを一つまたいでしまったようです
>pivot が fbx で持ってきたデータと一致しない問題、とりあえず手元では解決を確認できました。が、影響が大きい変更ゆえにどこか別の部分で問題が出ている可能性を否定できません。
お手数ですがそちらでも検証していただけますでしょうか。
ですが急ぎ拝見させていただきます
ありがとうございます

**Comment by i-saint** [comment]
テストデータ確認しました。
単純に namespace 対処漏れですね…。直しておきます。

**Comment by i-saint** [comment]
とりあえず更新版パッケージ。
[MeshSync_20190327_internal.zip](https://github.com/unity3d-jp/MeshSync/files/3011573/MeshSync_20190327_internal.zip)

namespace 除去はできていますが、テストデータの Unity 用データが欠けている？ようで整合性チェックはできていません。

**Comment by TsuPMC** [comment]
確認させていただきました
正しく再現できるようです
ありがとうございました

**Comment by TsuPMC** [comment]
>別件で恐縮ですが、pivot が fbx で持ってきたデータと一致しない問題、とりあえず手元では解決を確認できました。が、影響が大きい変更ゆえにどこか別の部分で問題が出ている可能性を否定できません。
お手数ですがそちらでも検証していただけますでしょうか。
MeshSync_20190326_internal.zip

について確認させていただきました

非skinningデータについては一致するようになりました
が、skinningデータについてMeshSync　scene内で意図しないtransform値が入るようになったようです

現象が再現できるテストデータを作成したのでご確認いただけますでしょうか
[Pivot_issue.zip](https://github.com/unity3d-jp/MeshSync/files/3017852/Pivot_issue.zip)

**Comment by i-saint** [comment]
ありがとうございます。再現取れました。
思ってたよりも厄介な問題のようです。以前のバージョンでも正しい結果にならないですね。

**Comment by i-saint** [comment]
少なくとも提供いただいたデータは正しく出るようになりました。お手数ですが確認お願いいたします。
Maya の skinning に絡む処理は非常に複雑であり、おそらくこのバージョンでも意図した結果にならない状況はあると思います。その時はお手数ですがまたテストデータをいただけると幸いです。

また、#51 のマテリアルの件も対応が入っています。
同名マテリアルがあった場合、編集可能な方を優先して割り当てるようにしています。FBX prefab に入っているマテリアルは編集不可能なので、結果的に要件を満たします。

[MeshSync_20190330_internal.zip](https://github.com/unity3d-jp/MeshSync/files/3024845/MeshSync_20190330_internal.zip)

**Comment by TsuPMC** [comment]
お早いご対応どうもありがとうございます
MeshSync_20190330_internal.zipについてただいま確認させていただいております
今のところ不具合は確認されておりません
念のためもう少し多くのデータで確認させていただきますのでまたご連絡申し上げます

**Comment by i-saint** [comment]
マイナーアップデート版です。
Maya 側の Animation の項目に "Keep Flat Curves" というチェックが増えています。これを有効にしておくと、キーフレームリダクションを有効にしつつ、全くアニメーションしないオブジェクトのキーも保ちます。Unity 側のアニメーションのインポートそのものも若干速くなっています。
あと、今回の件には関係ないかもしれませんが、Unity 側 MeshSyncServer のアニメーションの補間 ("Animation Interpolation") の Constant をちゃんと動くように直せました。アニメーションの補間を完全に無効にしたいケースがあれば役立つと思われます。

[MeshSync_20190410_internal.zip](https://github.com/unity3d-jp/MeshSync/files/3063217/MeshSync_20190410_internal.zip)

**Comment by TsuPMC** [comment]
ありがとうございます！
Constantも動くとは尚素敵です
早速試させていただきます

**Comment by TsuPMC** [comment]
"Keep Flat Curves"　について確認できました
キーフレームリダクションを有効にしつつ、今までならば全くanimationしないobjectはanimation clipが生成されなかったですが、"Keep Flat Curves"　にチェックを入れるとそういったobjectのanimation clipも生成できました

Constantも確認できました
Constantについては以下に現場の感想を述べさせていただきます
animation curveの種類はシーンで一律に決めるものでもないかもしれません
「キャラクターはリミテッドアニメーションで作る」からConstant Curveで作ったとしても
カメラのanimation curveはsmoothにしたいなどanimation curveは１シーン内に種類が混在することが多い気がいたします
またそもそもリミテッドアニメーションでもないものについてはanimation Curveの種類は１objectの中でも混在することでしょう　デザイナーは「この部分のanimationをどう表現したいか」でanimation curveを使い分けます

そういたしますと現状の「"Animation Interpolation"はUnityの方で一律Smooth/Constant/Linearの選択をする仕様」であるとあまり都合がよくないかもしれません
恐らく「mayaで設定したcurveの種類がそのまま再現される」が理想となるかと思われます

勝手を申しましたが今後の開発のご参考になれば幸いです

**Comment by i-saint** [comment]
フィードバックどうもありがとうございます。

やはり Constant は現状のままだと使いにくいですよね。DCC 側のカーブに合わせるのが理想なのですが、残念ながらこれは不可能に近いレベルで困難で、別の対策が必要だと感じています。
現状で一番現実的だと思っているアイデアは、Unity 側で sync 設定を上書きできるようにするコンポーネントを用意する、といったものになります。MeshSync で生成されたオブジェクトに対してそのコンポーネントを追加すると、以降 MeshSyncServer の設定よりもコンポーネントが持つ設定を優先する、といった具合です。
