### ISSUE TITLE
Compatible Unity versions?

### ISSUE THREAD

**Issue by kusogaki77** [unity3d-jp/MeshSync#54]
Unity 2018.3.6f1 と数日前に出たBlender2.8に利用しています。
meshsyncの最新バージョン「0315」はエラーなくインストールできますが、Auto-syncを有効にした上に、Blender側で編集するとUnity側に反映しません。

Unity 2018.3.6f1はしばらく使い続けるため、Blender2.8とMeshSyncのバージョンをそろわなければいけないでしょうか。

大雑把に言うと、Blender、Unityの　バージョンを　MeshSyncリリースの日付とできるだけ合わせればいいですか。

**Comment by i-saint** [comment]
Unity のバージョンは気にする必要はないはずです。2017.4 以降であればどのバージョンでも動作するようにしてあります。
Blender の 2.8 は事情が特殊で、ほぼ毎日新しいバージョンが出ており、その度にプラグインの互換性が失われる危険性があります。なので、MeshSync のリリース日と離れるほど動作しなくなる可能性が増します。beta が取れたらこの状況は落ち着くと思われますが、それまでは 2.79b を使うことをお勧めしています。
また、MeshSync のバージョンは Unity 側と Blender で揃える必要があります。揃っていなくても動作する組み合わせもありますが、基本揃えるべきものとご理解ください。

今、最新の Blender 2.8 (March 27, 01:09:24 - 337eb8c1de4c) で試したところ同期できたので、MeshSync のバージョンの不一致が起きているのではないかと推測します。
Blender の場合、事前に古い add-on を remove した後、Blender を再起動してインストールしないと更新が失敗するので、ここに原因があるかもしれません。

**Comment by kusogaki77** [comment]
ご丁寧に、詳しい説明　誠にありがとうございます。
諸々承知いたしました。本当に助かりました！

「2017.4 以降であればどのバージョンでも動作するようにしてあります。」
との事、見逃してしまい申し訳ございません。
