### ISSUE TITLE
20190423の更新についてご質問

### ISSUE THREAD

**Issue by TsuPMC** [unity3d-jp/MeshSync#60]
20190423版のリリースありがとうございます

確認させていただいたのですがカメラのanimationについてご質問があります
テスト環境は
maya2017 update5
Unity2018.2.9f1
です

以前まではカメラのanimationはSyncしてUnityに送られるとUnityの画角に変換されていたと思います
今回のリリースではPhysical Cameraのままと言いますか、画角がmayaのForcal Lengthのままになっていますが今回の更新でこちらの仕様に変更になったのでしょうか
![20190423cam](https://user-images.githubusercontent.com/39584741/56642101-b1d0b380-66b1-11e9-92e3-21cf6c8818e6.jpg)
![20190423cam2](https://user-images.githubusercontent.com/39584741/56642105-b4330d80-66b1-11e9-8c1a-1ffb71c43507.jpg)

**Comment by TsuPMC** [comment]
そうですか
承知いたしました　しょんぼり

**Comment by TsuPMC** [comment]
このバージョンでカメラのanimation clipをUnityで生成すると　UnityProjectであらかじめ用意したカメラのfbxアセットにanimationを合わせたときmayaのカメラと結果が一致しなくなってしまいました
fbxのカメラアセットはPhysical Cameraにチェックが入っています
何かおわかりになりますでしょうか

**Comment by i-saint** [comment]
情報ありがとうございます。
それは致命的にまずいので、根本的解決ではありませんが、"Use Physical Camera Params" 的なオプションを用意して一旦デフォルトでオフにします。

**Comment by TsuPMC** [comment]
mayaとUnityのテストシーンをお送りします
ご確認いただけますでしょうか

[190425MStest.zip](https://github.com/unity3d-jp/MeshSync/files/3116481/190425MStest.zip)

**Comment by TsuPMC** [comment]
上記ですが
mayaは2017 Update5
Unityは2018.2.9f1でテストしています

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/MeshSync/releases/tag/20190902
