### ISSUE TITLE
OpenSubdiv support

### ISSUE THREAD

**Issue by i-saint** [unity3d-jp/MeshSync#63]
not so high priority, but this is one of a cause of DCC / Unity inconsistency.
it will be tricky. if we to support skinning with subdiv, we must apply subdiv **before** skinning. that means we must apply subdiv for bone weights.

**Comment by crogersarvr** [comment]
Hey I-Saint, I was looking in adding quad support for the maya->unity pipeline.  It looks like some of the code paths for SetIndices and not SetTriangles are there.  Where does it triangulate a quad mesh, in the maya c++ plugin or in the unity c++ plugin? Why is the re-indexing and re-topology done? Can i just skip it the meshRefiner? 
I had tried to add that support to the existing mesh enity but now i am looking at creating a new entity type or just sending an fbx file (supports quads) through server as a file entity type.
Any other advice?   thanks for sharing this cool tool.

**Comment by i-saint** [comment]
re-indexing is inevitable because points, normals, UVs can have independent topology on most of DCC tools. it's a familiar problem for all of who had written mesh importer for realtime rendering.
I recommend you to write a simple mesh importer to understand the problem and learn the fundamentals of content pipeline. FBX SDK is good for it (it's well-documented and maintained).
