### ISSUE TITLE
20190423の更新版でのご質問　animation clipの置き換えについて

### ISSUE THREAD

**Issue by TsuPMC** [unity3d-jp/MeshSync#64]
20190423版を試しまして生成されたanimation clipの更新についてご質問があります

生成されたanimation clipですが一度Timelineに組み込んだ後、mayaでanimationの修正をしてMeshSyncでanimation clipをSyncしなおすとmetaデータも書き換えられてしまうようになり、Timelineに組み込んでいたanimation clipがLostしてしまうようになりました（これは3/30にIssues#53で下記ご対応いただいたバージョン（MeshSync_20190330_internal.zip）から起きていたようです　すみません　今日まで気づきませんでした）

Issues#53
「少なくとも提供いただいたデータは正しく出るようになりました。お手数ですが確認お願いいたします。
Maya の skinning に絡む処理は非常に複雑であり、おそらくこのバージョンでも意図した結果にならない状況はあると思います。その時はお手数ですがまたテストデータをいただけると幸いです。

また、#51 のマテリアルの件も対応が入っています。
同名マテリアルがあった場合、編集可能な方を優先して割り当てるようにしています。FBX prefab に入っているマテリアルは編集不可能なので、結果的に要件を満たします。」

**Comment by TsuPMC** [comment]
文章の途中で送信してしまいました　すみません
上記ですが以前のバージョンでは起きていません

こちらは以前のように.metaデータは置き換わらないようにはなりませんでしょうか
もしくは何かチェック項目が足されているのをこちらで見落としているなどありますでしょうか

**Comment by i-saint** [comment]
すみません、心当たりあります。戻します。

**Comment by i-saint** [comment]
こちらのパッケージを試していただけますでしょうか。physical camera params 一時無効化も適用済みです。
[MeshSync.zip](https://github.com/unity3d-jp/MeshSync/files/3113216/MeshSync.zip)

**Comment by TsuPMC** [comment]
ありがとうございます
カメラは元に戻りましたがanimation clipの.metaデータはまだ書き換わってしまいます

**Comment by i-saint** [comment]
上記パッケージで改めてテストしていますが、私の手元では .meta の更新は確かに起きなくなっています。
そちらでは、最小限の構成 (Cube 一個、位置だけアニメーションなど) でも .meta 更新は起きていますでしょうか？

**Comment by TsuPMC** [comment]
animationの.metaデータの更新ですが
下記挙動でanimationの.metaが書き換わりました

①　新規sceneにmayaからmodelとanimationをMeshSyncしてsceneを保存
②　①のMeshSyncSceneを再び開いて、MeshSyncServerからmodelを削除
③　mayaからmodelとanimationをSync

②でMeshSyncServerからmodelを削除しなければ.metaは書き換わらないようですが

これは仕様でしょうか
（以前からそうだったようですが確認できていませんでした）

**Comment by TsuPMC** [comment]
↑上記追記します　maya内でモデルの更新はありません
ただ「HierarchyのMeshSyncServer以下からmodelを削除」して再びmodel とanimationをSyncしました

**Comment by i-saint** [comment]
元々そういう仕様です。
sync 先オブジェクトが既に AnimationClip を持っているならそれを再利用、そうでなければ新規に生成、という内部処理になっています。Assets 内のアセットは考慮していません。

**Comment by i-saint** [comment]
「上書き作成する場合でも .meta はキープする」はできそうです。確かにほぼ全ての状況でこの方が望ましいと予想されるので、やってみます。

**Comment by TsuPMC** [comment]
どうもありがとうございます！
助かります

**Comment by i-saint** [comment]
対応できたと思います。確認していただけると幸いです。
[MeshSync.zip](https://github.com/unity3d-jp/MeshSync/files/3122011/MeshSync.zip)

**Comment by TsuPMC** [comment]
ありがとうございます
試してみます！

**Comment by TsuPMC** [comment]
遅くなりまして申し訳ございません
確認できました
「上書き作成する場合でも .meta はキープする」はできるようになりました
どうもありがとうございました
