### ISSUE TITLE
 The specified procedure could not be found.  (MeshSyncClientMaya)

### ISSUE THREAD

**Issue by chrisrogers3d** [unity3d-jp/MeshSync#66]
I copied the plugins and scripts to my user/Documents/maya.  When I try to load the plugin, I get this error:
`// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: Unable to dynamically load : C:/Users/christopher.rogers/Documents/maya/plug-ins/MeshSyncClientMaya.mll
The specified procedure could not be found.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: The specified procedure could not be found.
 (MeshSyncClientMaya) // `

Maya 2018.5, Windows10, Unity2019.1

**Comment by chrisrogers3d** [comment]
It seems the plugin is compiled for Maya 2019.

**Comment by chrisrogers3d** [comment]
Is there a compiled .mll for 2018?

**Comment by chrisrogers3d** [comment]
User error. I found the 2018 version.

**Comment by i-saint** [comment]
I recommend you to copy "modules" dir in the archive to your "C:/Users/christopher.rogers/Documents/maya". after that, Maya will select the appropriate version of plugin automatically.
