### ISSUE TITLE
Should MeshSync correct mesh to use Y-up on export?

### ISSUE THREAD

**Issue by bitinn** [unity3d-jp/MeshSync#67]
I am using MeshSync with Blender 2.8 and found that it decides to rotation gameobject instead of fixing the mesh coordinate (from Z-up to Y-up).

I think it's fine to keep the Z-up in scene view, but on "Export Mesh", I would say it's more appropriate to convert them into Y-up. Perhaps there should be a toggle to allow changing this behavior?

**Comment by i-saint** [comment]
thanks for the feedback.

actually, the previous version of MeshSync converted the coordinate of each vertex from Z-up to Y-up. I changed to current behavior to align FBX importer's behavior.
(if you export a mesh from Blender as FBX and import it to Unity, you can confirm meshes are still Z-up and X angle of root GameObject is -90)
but as you point, keep "per-vertex convert" mode as an option or add "export meshes with coordinate conversion" is a good idea. I will try.

**Comment by bitinn** [comment]
> (if you export a mesh from Blender as FBX and import it to Unity, you can confirm meshes are still Z-up and X angle of root GameObject is -90)

Thx, I saw your release note.

But I am not certain about this behaviour, here is a quick test (using Blender 2.8, 2019-04-24 build):

### FBX

<img width="519" alt="Screen Shot 2019-04-27 at 18 15 41" src="https://user-images.githubusercontent.com/1484279/56848182-80a5ec80-6918-11e9-887a-8472ec79085b.png">

<img width="239" alt="Screen Shot 2019-04-27 at 18 13 58" src="https://user-images.githubusercontent.com/1484279/56848166-42a8c880-6918-11e9-900d-1290dec37dd8.png">

<img width="318" alt="Screen Shot 2019-04-27 at 18 16 53" src="https://user-images.githubusercontent.com/1484279/56848194-aaf7aa00-6918-11e9-886f-0e786ec26458.png">

<img width="320" alt="Screen Shot 2019-04-27 at 18 16 39" src="https://user-images.githubusercontent.com/1484279/56848197-b054f480-6918-11e9-9726-b182f21e9c24.png">

### OBJ

<img width="240" alt="Screen Shot 2019-04-27 at 18 18 48" src="https://user-images.githubusercontent.com/1484279/56848223-ef834580-6918-11e9-92d7-4fcdb0891346.png">

<img width="235" alt="Screen Shot 2019-04-27 at 18 18 53" src="https://user-images.githubusercontent.com/1484279/56848225-f01bdc00-6918-11e9-8860-55d18bec0566.png">

<img width="316" alt="Screen Shot 2019-04-27 at 18 19 21" src="https://user-images.githubusercontent.com/1484279/56848234-0cb81400-6919-11e9-8831-f237777f5300.png">

<img width="318" alt="Screen Shot 2019-04-27 at 18 19 26" src="https://user-images.githubusercontent.com/1484279/56848236-0d50aa80-6919-11e9-8b2f-b40774a950a6.png">

### Comment
 
- I don't use FBX a lot so I can't tell if this is the correct export settings, but I try to match its settings to my OBJ export config.
- I believe the exported FBX should be Y-up, or at least contain Y-up information for game engine and DCC to read.
- But I find Unity's behaviour quite troubling, because it display the model as Z-up in inspector, but when you drag and drop it to the scene, it uses -90 x rotation to "correct" display for a Y-up scene. This information is not exposed anywhere under inspector, and is likely going to cause confusion.
- I did notice setting `!EXPERIMENTAL! Apply Transform` flag on export will allow Unity to import the model as Y-up, but I think this is a hack to accommodate older DCC (not sure about this one).
- My preference would be to export mesh like OBJ, where it's clearly Y-up, and Unity will import them as Y-up, and display them as Y-up without rotation. Consistent, and no confusion.

**Comment by sasa42** [comment]
Hi. 
FYI. Here some good overview about some workarounds with an script to handle fbx export issues.
https://youtu.be/bpH5ZfonExo

However when you need correct behaviour for all cases you need to convert Blenders right-handed (+Z up) to Unity’s left-handed (+Y up). 
Here is an Unity PostProcessor script who does it right for all cases in special for rotations.
https://www.edy.es/dev/2014/02/a-better-blender-to-unity-3d-importer/

Features...
“My script imports the Blender file into Unity 3D as expected:

Complete hierarchies are preserved with their correct transforms (position, rotation, scale).
No artificial rotations are imposed in the imported model: if a rotation in Blender was [0,0,0] the rotation in Unity will be [0,0,0].
Optionally the forward orientation can be reversed for matching the Unity’s convention (+Z).
Keyframe-based animations in Blender are correctly converted to animation clips in Unity. The animations will look the same in both Blender and Unity.
...
“

Do you think same behaviour would be possible in live MeshSync doing all these quaternion operations in realtime?

**Comment by i-saint** [comment]
thanks for the feedback.
as noted in https://github.com/unity3d-jp/MeshSync/issues/67#issuecomment-487268063, you can choose conversion algorithm on next version. it was already implemented in dev branch and working fine.

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/MeshSync/releases/tag/20190902
