### ISSUE TITLE
Unity and Blender 3.1 install addon?

### ISSUE THREAD

**Issue by enzyme69** [unity3d-jp/MeshSync#678]
I manage to install MeshSync package on my Unity on Mac (M1). But I am not seeing option under preference to install addon for my DCC Blender 3.1. 

<img width="694" alt="Screen Shot 2022-05-09 at 2 42 35 pm" src="https://user-images.githubusercontent.com/3952687/167342007-c1fb3011-ed5b-4d4c-8d88-219d749bee4b.png">

Did I do anything wrong?

**Comment by sindharta** [comment]
That is strange. Do you see any errors in the Console window ?

**Comment by enzyme69** [comment]
It could be versioning (Unity?) or also how I install it wrong, but my Blender app and Unity MeshSync does not seem to work properly. I tried different version, now I can see DCC but still cannot install:

<img width="743" alt="Screen Shot 2022-05-10 at 11 05 38 am" src="https://user-images.githubusercontent.com/3952687/167522357-370561d0-0b02-453d-9347-df1041e08862.png">

**Comment by enzyme69** [comment]
<img width="1028" alt="Screen Shot 2022-05-10 at 11 28 47 am" src="https://user-images.githubusercontent.com/3952687/167524440-398b5be5-28b3-4f10-8182-581a5d51a636.png">

Seems to work with latest official 3.1. I will study this further thanks!

**Comment by sindharta** [comment]
No problem.

FYI, [MeshSyncDCCPlugins](https://github.com/Unity-Technologies/MeshSyncDCCPlugins) doesn't support Blender 3.2 and 3.3 yet as they haven't been officially released.
You could in theory build the plugins yourself and install the plugins manually, although you need to get the source of Blender 3.2 and 3.3, and I don't know where they are located.
