### ISSUE TITLE
Using MeshSync for editor time only.

### ISSUE THREAD

**Issue by pshtif** [unity3d-jp/MeshSync#679]
Currently there seems to be no way to use MeshSync on Android project even for its editor capabilities. We need to switch to PC project on an extra branch and then sync it to main branch where we deploy to Android. Due to multiple issues:

- MeshSync checks if project is STANDALONE even for its editor time functionality for some reason
- MeshSync has runtime DLLs which we don't use but can't build anyway

Is there a plan to clean it up so MeshSync is usable for editor time syncing without having PC dependency?

Thanks.

**Comment by sindharta** [comment]
We are focusing on PC/Mac/Linux only at the moment, but I'll put this in our backlog.
Thank you for the feedback.

**Comment by FUJonathan** [comment]
I would also like to request editor-only support for Android and iOS as well. We target both Android and iOS but our project has a lot of assets so switching platforms eats up a lot of time for the reimport. We only need to use MeshSync in the editor so we would greatly appreciate it if there were a way to use it without switching platform.

Thank you in advance.

**Comment by pshtif** [comment]
@FUJonathan since it doesn't seem they are going to do it I already forked it to our internal repo and did a Editor only version that works for mobile projects since we do only Android/iOS only. If there is interest I may put it on Github as well.

**Comment by sindharta** [comment]
We will do it at some point, but it's just not the top priority for us at the moment.
But if you have already implemented it in your repo, you are welcome to give us a PR.

**Comment by marek-jelo-jelinek** [comment]
Hi, @sindharta this should be a graceful fix

https://github.com/unity3d-jp/MeshSync/pull/689

**Comment by sindharta** [comment]
This fix has been released in `0.13.2-preview`.
Thank you for your contribution, and feel free to reopen this issue if necessary.
