### ISSUE TITLE
Should MeshSync allow users to set default renderer or components?

### ISSUE THREAD

**Issue by bitinn** [unity3d-jp/MeshSync#68]
The idea is this:

- Instead of using SkinnedMeshRenderer by default, perhaps users could set a custom prefab as the "template object".
- On sync, new objects will be created using this template object, and sharedMesh/transform for each object will be set accordingly.
- MeshSync workflow appears to be designed for character models, but I find this tool quite useful for modular asset modeling: where we export many objects in batch.
- Being able to set custom Renderers (like MeshRenderer instead of SkinnedMeshRenderer) or even custom Components, are great for this workflow.

**Comment by i-saint** [comment]
on next version, non-skinned meshes will be rendered with MeshRenderer instead of SkinnedMeshRenderer (#76)
your suggestion is understandable, but it is too complex to maintain. if you need that level of customization, you would better to make changes to source code (MeshSyncPlayer.cs etc)
