### ISSUE TITLE
Sync empty objects

### ISSUE THREAD

**Issue by FlorianBarnier** [unity3d-jp/MeshSync#681]
I'm using this tool since a couple days to make level design directly from Blender and I must say it's awesome, though one thing that I feel is missing is synchronisation of empty objects. This would be great to place stuff like triggers directly in the scene, or to automate some things (e.g. making a script listening to _OnPostRecvMessageCallback_ to scan the content and auto add components or prefabs to objects with a specific name).

**Comment by sindharta** [comment]
Do you have a specific use case/sample of what you are trying to achieve ?

**Comment by FlorianBarnier** [comment]
Sure, here's an example. I need triggers in tons of places in my level, so I use empties in Blender as reference to know where they should be:
<img width="225" alt="Capture d’écran 2022-05-12 à 11 34 03" src="https://user-images.githubusercontent.com/62941304/168040418-1844eb9d-0098-41c3-9967-9c68977f1e21.png">
Currently, every time I make a layout change in Blender, I have to move around the actual triggers in Unity to match with the new positions (which happens quite a lot).

If empties were synchronized, I could simply add the trigger components on them in Unity and then move them directly from Blender, instead of having to do the work twice.

-----

Here's another example:
<img width="200" alt="Capture d’écran 2022-05-12 à 11 48 03" src="https://user-images.githubusercontent.com/62941304/168043242-c789ab87-8a30-403c-8f75-8452004265a5.png">
If empties were synchronized, I could simply have an empty (the cube on the image) on this torch, with a specific name like _ParticleSystem_Torch_. Then, in Unity, I could make a script listening to _OnPostRecvMessageCallback_ to know when the scene has been updated, and automatically attach a fire particle system on every empty named _ParticleSystem_Torch_.

**Comment by sindharta** [comment]
Interesting ! Thank you very much. 
We'll consider this.

**Comment by schinkowski** [comment]
Thank you for your feedback @FlorianBarnier.
This should work in version 0.16.

**Comment by FlorianBarnier** [comment]
That's great to hear, thanks!

**Comment by sindharta** [comment]
Closing this for now. Please feel free to reopen if you think the issue still applies.
