### ISSUE TITLE
Built-in "Overlay.mat" is serialized in 2019.x, thus will not work in older versions.

### ISSUE THREAD

**Issue by bitinn** [unity3d-jp/MeshSync#69]
I mean the material under `Runtime/Materials/`

But to be honest, I don't know when this material is used; I just recreated it under Unity 2018.3, and face no issues so far.

**Comment by i-saint** [comment]
thanks for the feedback.

I will remove Overlay.mat from next release. it is a material purely for debug. (visualize normals, vertex colors, UVs, etc)

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/MeshSync/releases/tag/20190902
