### ISSUE TITLE
Unity: Preferences  -> MeshSync Do not show

### ISSUE THREAD

**Issue by y5-nakajima** [unity3d-jp/MeshSync#711]
use
Unity 2020.3.2
MeshSync 0.6.1-preview
MeshSync DCC Plugin-0.6.0-preview
*using this version to work with MotionBuilder.
![スクリーンショット (62)](https://user-images.githubusercontent.com/83809984/178438856-a92f0575-b9fa-4e6a-9d89-ad0ed7c310da.png)

There was no information in the document. Am I missing some steps?

**Comment by sindharta** [comment]
Unfortunately, MotionBuilder is currently not supported yet via the installation method in the Preferences window, and therefore [manual installation](https://github.com/Unity-Technologies/MeshSyncDCCPlugins/blob/dev/Documentation~/en/Installation.md#motionbuilder) is necessary.
