### ISSUE TITLE
Alpha value of vertex color not going from 3DS Max to Unity.

### ISSUE THREAD

**Issue by pshtif** [unity3d-jp/MeshSync#716]
Hi guys we encountered an issue with our vertex color pipeline using MeshSync. It seems the alpha value for the vertex color is not getting synced to Unity. 

https://user-images.githubusercontent.com/396413/179503900-68ec8bb9-7d48-422f-8b1f-08e100786dd9.mp4

**Comment by sindharta** [comment]
Would it be possible for you to attach your asset, so that we can be sure that our fix fixes the issue  ?

**Comment by mkolcun** [comment]
Hi there.
Here is the exact file @pshtif reported we struggle with.
[factory_decor.zip](https://github.com/unity3d-jp/MeshSync/files/9141883/factory_decor.zip)
.

**Comment by sindharta** [comment]
Thank you.
My colleague just helped me realize this, but did you mean 3ds Max ? (as seen in the video ?)
Or are we missing something because the title of this issue is 

"Alpha value of vertex color not going from Blender to Unity"

**Comment by mkolcun** [comment]
There was misunderstanding in a bug report on our side. I apologize.
The problem is in pipeline 3DS Max > Unity. Blender > Unity transfers alpha property correctly.

**Comment by sindharta** [comment]
Can you please try `MeshSync@0.14.2-preview`  and update your 3dsMax plugin ?

**Comment by mkolcun** [comment]
@sindharta Thank you. After update, it seems alpha values are transferred properly and our use-case issue is solved.
