### ISSUE TITLE
Doesnt work in editor when targeting android.

### ISSUE THREAD

**Issue by wewrere41** [unity3d-jp/MeshSync#717]
0.13.2-preview.
 Unity 2020.3.19f1
![image](https://user-images.githubusercontent.com/45511976/179749236-86209ce3-d3b1-4411-9e72-6da798c4e92e.png)
![image](https://user-images.githubusercontent.com/45511976/179749275-905c10fd-2a61-4810-894e-804fd967977b.png)
![image](https://user-images.githubusercontent.com/45511976/179749289-4ffb8cf7-f450-46ef-9dba-92ec00758f7c.png)

**Comment by sindharta** [comment]
So, to clarify:
1. Android runtime support is not yet implemented. Issue: https://github.com/unity3d-jp/MeshSync/issues/110
2. Editor support for projects targeting Android (or iOS) is supported starting from 0.13.2-preview.
https://github.com/unity3d-jp/MeshSync/issues/679

I suppose you were referring to the 2nd one based on your previous question ?

**Comment by wewrere41** [comment]
Yes 2nd. It doenst work when targeting android. 
Unity 2020.3.19f1
![image](https://user-images.githubusercontent.com/45511976/179749236-86209ce3-d3b1-4411-9e72-6da798c4e92e.png)
![image](https://user-images.githubusercontent.com/45511976/179749275-905c10fd-2a61-4810-894e-804fd967977b.png)
![image](https://user-images.githubusercontent.com/45511976/179749289-4ffb8cf7-f450-46ef-9dba-92ec00758f7c.png)

**Comment by sindharta** [comment]
So, that means Android runtime build, right ?

**Comment by wewrere41** [comment]
No, its Editor. I don't say runtime build.

Sindharta Tanuwijaya ***@***.***>, 20 Tem 2022 Çar, 05:00
tarihinde şunu yazdı:

**Comment by sindharta** [comment]
Hm, you are right. Let us take a look and get back to you

**Comment by sindharta** [comment]
Can you please try `MeshSync@0.14.2-preview` ?

**Comment by wewrere41** [comment]
> Can you please try `MeshSync@0.14.2-preview` ?

Thank you  ,it works. But it doesn't sync materials with blender. It does not support?
Edit: It doesn't sync material changes in blender. I have to export mesh and import mesh again in blender. And its gets materials correctly on unity.
And materials doesnt sync when using URP because MeshSync using "_Color" property for color  and urp shader using "_BaseColor" for color.

**Comment by sindharta** [comment]
@wewrere41 your above comments are duplicate with https://github.com/unity3d-jp/MeshSync/issues/743 and I will address your comments there as they are unrelated to this current issue.

**Comment by sindharta** [comment]
I guess we can close this current issue now then ?
~~Have you confirmed that it works in the editor even if it targets Android ?~~

> Thank you ,it works

Ah, missed your first sentence up there. Ok, closing this issue.
