### ISSUE TITLE
Blender 2.8 closing when trying to sync with Unity

### ISSUE THREAD

**Issue by ilhankeskin** [unity3d-jp/MeshSync#72]
When trying to sync objects with 05/09/2018 blender 2.8 build after clicking sync button blender closing.

**Comment by i-saint** [comment]
thanks for the info.
it seems plugin compatibility was broken again. Blender 2.80 is updated almost every day and each update can break the plugin compatibility.
we will release a new version soon that supports latest Blender 2.80. but this can happen again until the end of beta.

**Comment by ilhankeskin** [comment]
ahh okey thanks for reply back very quickly
Is there any blender 2.8 version works link could you share with me I deleted all older versions from my computer and cant find them on the internet right now

**Comment by i-saint** [comment]
it seems they don't keep archives of non-latest versions of 2.80.
but fortunately, I could build the plugin for the latest 2.80. this should work:
[UnityMeshSync_Blender_Windows.zip](https://github.com/unity3d-jp/MeshSync/files/3160979/UnityMeshSync_Blender_Windows.zip)

(I assume your OS is Windows)

**Comment by bitinn** [comment]
@i-saint is there a quick guide for building a macos build myself? I needed latest blender for another addon and just realize it breaks meshsync...

**Comment by i-saint** [comment]
@bitinn
1. clone Blender source (git://git.blender.org/blender.git)
2. clone MeshSync source 
3. extract Blender headers
    - move to MeshSync\.MeshSync\Plugin\MeshSyncClientBlender\tools
    - python extract_headers.py [path to cloned blender source]
    - copy extracted headers to MeshSync\.MeshSync\Plugin\External\blender-2.80\include
4. build plugin
    - build_blender.bat or MeshSync_Blender.bat

possibly it doesn't compile because of changes in Blender sources. in that case, you need to update sources in MeshSyncClientBlender by yourself.

**Comment by bitinn** [comment]
@i-saint I might be missing something in this step:

> build_blender.bat or MeshSync_Blender.bat

I don't think these scripts would work on macOS?

I tried to setup my build script through VS Code:

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "msbuild",
            "args": [
                ".MeshSync/Plugin/MeshSyncClientBlender.vcxproj",
                "/p:Configuration=Release",
                "/t:Build",
                "/p:Platform=x64"
            ],
            "group": "build",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}
```

But the project expects Visual Studio, right? I can't get pass this line (even if I setup other MeshSync specific environment variables.)

```
<Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
```

**Comment by i-saint** [comment]
I assumed your OS is windows. you need to use cmake on non-Windows.

**Comment by i-saint** [comment]
continue to #89

**Comment by bitinn** [comment]
Thx for working on it, just a quick note, don’t build against RC1, it has a code-signing issue on macOS that cause some addons using ctype to fail, make you build on RC2 (or beta, which is unsigned)

(From my phone)

**Comment by i-saint** [comment]
thanks for the info!
