### ISSUE TITLE
Workspace is no longer a valid bl_context

### ISSUE THREAD

**Issue by bitinn** [unity3d-jp/MeshSync#74]
Not sure what it is now, but neither `bl_context = ".workspace"` nor `bl_context = "workspace"`works to show the panel in Blender.

I resort to using `bl_context = "scene"` for now. (But still need a custom macOS build to make sync work with latest Blender.)

**Comment by i-saint** [comment]
thanks for the info.

**Comment by i-saint** [comment]
FYI: this change revives MeshSync in Workspace.
https://github.com/unity3d-jp/MeshSync/commit/4be07179e03a181f47786e5109acdcb84870f796

**Comment by i-saint** [comment]
continue to #89
