### ISSUE TITLE
The tool doesn't appear on the workspace

### ISSUE THREAD

**Issue by Sparking2** [unity3d-jp/MeshSync#75]
In the newest blender 2.8, after I install the plugin and active it, it doesn't show up where is showed in the image on the instructions, or in any other area.

**Comment by i-saint** [comment]
#74 #72

**Comment by Sparking2** [comment]
oh thank you, I would try the version in the #72

**Comment by sasa42** [comment]
workspace stays empty for versions blender 2.8 from may 17 to jul 12.
also tried #72

**Comment by i-saint** [comment]
continue to #89
