### ISSUE TITLE
Unskinned Maya mesh is skinnedMeshRenderer in Unity

### ISSUE THREAD

**Issue by crogersarvr** [unity3d-jp/MeshSync#76]

**Comment by crogersarvr** [comment]
When I sync regular maya meshes with my unity scene, it creates skinnedMeshRenderers instead of meshRenderers, which breaks my unity scripts.

**Comment by i-saint** [comment]
I know it is undesirable behavior in some cases, but it is intended. skinned or non-skinned (and have blendshapes or not) can be easily switched in DCC side. but switching MeshRenderer and SkinnedMeshRenderer is complicated in Unity and can cause unexpected result. so we are always using SkinnedMeshRenderer.
probably we need to add "use MeshRenderer for non-skinned meshes" mode.

**Comment by crogersarvr** [comment]
Thank you for the reply!
I will be adding that and will make a pull request in the next week.

Have a good day

Chris

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/MeshSync/commit/fe5c2a0be3a4cc48579f8d88e99bd7f41bb62ae9

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/MeshSync/releases/tag/20190902
