### ISSUE TITLE
20190423版をBlenderに適応した時のエラー

### ISSUE THREAD

**Issue by cyross** [unity3d-jp/MeshSync#78]
初めて投稿いたします。
今般、MeshSyncをMetasequireに適応したので、今度はBlenderに適応することにして2.79に解説画面通りに適応すると、以下のエラーが出ました。

![unity_mesh_syncのエラーメッセージ](https://user-images.githubusercontent.com/34980/60077884-e0c4dd80-9765-11e9-8aca-d0026be7771f.png)

どうも何か見落としているようですうが…

使用しているBlenderは2.79(2019-05-23版・64bit)、使用OSはWindows10 64bitです。

あと、Blender2.8beta(2019-06-19)に適応しても、コンテクストメニューにMeshSyncの項目が現れないことも追記しておきます。

![blender28_001](https://user-images.githubusercontent.com/34980/60078522-0c949300-9767-11e9-9100-cbb8834ce9e3.png)

**Comment by i-saint** [comment]
レポートありがとうございます。

Blender 2.79 は、現行メジャーリリースの 2.79b ( https://www.blender.org/download/ ) でお試しください。
nightly build 版 ( https://builder.blender.org/download/ ) は、2.79 を名乗ってはいますがメジャーリリース版とは別物になっており、MeshSync の互換性も失われています。nightly build は基本的に開発者のためのものであり、強い理由がない限りはメジャーリリース版を使うことをおすすめいたします。(この旨ドキュメントに明記しておきます)

2.80 版は、来週対応版を出します。
ただ、2.80 は毎日更新され、更新のたびにプラグインの互換性が失われる可能性があるため、運が悪いと対応版も翌日の Blender 2.80 ではもう動かなくなっているということもありえます。Blender 2.80 のメジャーリリースが出るまではこの状況が不可避であることをどうかご理解ください。
(2.79 の nightly build 版に関しても同様で、互換性がすぐに失われる可能性が高いため対応を諦めている、という背景があります)

**Comment by cyross** [comment]
> Blender 2.79 は、現行メジャーリリースの 2.79b ( https://www.blender.org/download/ ) でお試しください。

2.79bで問題なくインストールできることを確認いたしました。ただ、インストールしてSyncできるようではあるのですが、Unityのシーンをシンクロできずに困っております(Blenderの画面はAutoSyncしてもManualSyncしてもBlenderの画面は初期のCube一つのまま。Cubeを動かすとUnityの画面でもシンクロしているので完全にシンクロしていないわけではないのですが…)。

使用しているUnityは2019.1.7fです。

2.80の件、お待ちしております。

**Comment by i-saint** [comment]
Unity のシーンを、というのは、Unity から Blender への同期という意味でしょうか。これはサポートしておりません。
Unity シーン情報をエクスポートしたい場合、リアルタイムではありませんが、package manager から取得できる FBX exporter が最も実用に耐える手段になると思われます。

**Comment by cyross** [comment]
>Unity のシーンを、というのは、Unity から Blender への同期という意味でしょうか。これはサポートしておりません。
説明不足でした。Metasequire版の「Unityのシーンをインポート」ボタンのような機能はないのかなというイメージでしたが、シーンの同期は無いということで理解しました。

FBX Exporterで試してみます。

**Comment by i-saint** [comment]
continue to #89
