### ISSUE TITLE
Blender 3.3 install fails

### ISSUE THREAD

**Issue by ModerateWinGuy** [unity3d-jp/MeshSync#782]
When clicking the install plugin to blender 3.3 it fails and shows this error in the unity console:
`[MeshSync] Error when installing plugin for Blender 3.3. 
 Message:  Can't find blender-3.3*.zip in MeshSyncDCCPlugins package`

**Comment by sindharta** [comment]
Blender 3.3 is not supported yet at the moment.
Stay tuned though.

**Comment by sindharta** [comment]
Blender3.3 is now supported in MeshSync@0.15.0-preview

**Comment by sindharta** [comment]
Closing. Please reopen if there is any issue.
