### ISSUE TITLE
Crashes when attempting to Manual or Auto Sync

### ISSUE THREAD

**Issue by David-Everlasting-Media** [unity3d-jp/MeshSync#810]
Blender 3.3.1 
Unity 2021.3.9f1
MeshSync 15.0-preview and 15.1-preview

I remember using this a while back with Unity 2020 and 2019 and had few if any issues. 

Now it seems I cannot even connect/sync without crashing Blender. 

At first I assumed the port was being blocked when it seemed I was unable to connect. My internal firewall seemed to be at blame. So I created a new outbound rule for the port Unity's Mesh Sync Server object had selected. 

When I manually match the Blender port to the Unity server port Blender just crashes, blanked out of existence. I've tried it several times, and it's always the same. It fails to sync until I manually match the port in Blender, but then it just blanks out of existence in the same instant. 

Any help would be appreciated.

**Comment by sindharta** [comment]
Thank you for the report.
The previous version of the DCC plugin for Blender (0.15.0-preview) has issues with Blender 3.3, so just to be sure, can you please attach a picture of the plugin version in Blender ?

Something like this:
![image](https://user-images.githubusercontent.com/7379311/197754969-98fe0877-dd37-4f01-8993-e2de42d7f12b.png)

Also, is your model using a certain feature in Blender, or does it crash just with the default scene (box) ?

**Comment by schinkowski** [comment]
Hi @nubbyninja. 

Thank you for your issue report.

To help us debug this, could you please send us a crash log? (https://docs.blender.org/manual/en/dev/troubleshooting/crash.html)

These steps should get the log:
- before running meshsync, save the blend file as test.blend
- run meshsync and wait for it to crash
- go to %TEMP% in explorer (if you're on windows)
- there should be a crash log in that folder called test.crash.txt
- post what's in the file

**Comment by ryantrawick** [comment]
Not the original poster but I am facing the same issue; instant crashing when I try to auto or manual sync in Blender.

I'm using Blender 3.2, Unity 2021.3.11f1, and MeshSync 0.15.1-preview with DCC Plugin 0.15.2-preview.

Here's the crash log:
[SyncTest.crash.txt](https://github.com/unity3d-jp/MeshSync/files/10044111/SyncTest.crash.txt)

**Comment by sindharta** [comment]
Thank you for the feedback.
Would it be possible for you to send us your sample file as well ?

**Comment by David-Everlasting-Media** [comment]
Hi folks. Sorry for the dropoff here. I'll append the requested files/data asap. Things have been a little crazy here. I'll get this to you by COB tomorrow.

**Comment by ryantrawick** [comment]
@sindharta 

Here it is: https://drive.google.com/file/d/19RNE45acJI36Ha3XhaPQ-cXGvFsMeu9A/view It's just the default blender scene though.

I'm going to update to the latest version of Blender and see if that fixes it, but looking at where it's crashing in the python script it seems it might be a server connection issue.

EDIT: Alright I updated to blender-3.3.1+lts.b292cfe5a936 and MeshSync is working well. One issue is that adding a Geometry Nodes modifier crashes blender if auto-sync is on before adding the modifier, but if I add the modifier before syncing then it works like normal.

Here's the crash log for that, this probably needs a new issue but it's not something that prevents me from working: 
[SyncTest.crash.txt](https://github.com/unity3d-jp/MeshSync/files/10059217/SyncTest.crash.txt)

**Comment by sindharta** [comment]
Thank you. Your description of the steps to repro the issue really helped.
We'll take a look at this.

**Comment by schinkowski** [comment]
We fixed a few crash issues in version 0.16.
Could you please try again and let us know if it's fixed?

**Comment by sindharta-tanuwijaya** [comment]
Closing.
Please feel free to reopen if necessary
