### ISSUE TITLE
Linked meshes not interpreted as instances

### ISSUE THREAD

**Issue by GuillaumeCauvet** [unity3d-jp/MeshSync#814]
Current behavior :
1. Made a mesh in Blender : MyObject
2. Duplicated it with Alt+D (Linked) : MyObject.001 MyObject.002
3. In Unity MyObject's mesh is MyObject, MyObject.001's mesh isMyObject.001 and MyObject.002's mesh is MyObject.002

Intended behavior :
MyObject, MyObject.001, MyObject.002 unity object should all use MyObject's mesh as an instance.

**Comment by sindharta** [comment]
Thank you very much for the report !
We have put this in our backlog for now.

**Comment by sindharta-tanuwijaya** [comment]
This has been fixed in `0.17.1-preview`.
Feel free to reopen the issue if necessary.
