### ISSUE TITLE
Mesh::mergeMesh don't merge attributes correctly.

### ISSUE THREAD

**Issue by Puppy-M** [unity3d-jp/MeshSync#868]
For example, in this per-vertex judgment，`base.size()== points.size()` should be `base.size()== num_points_old`,because the points have been inserted above.
``` c++
"msMesh.cpp"

auto expand_vertex_attribute = [&](auto& base, const auto& add) {
...
        if ((base.empty() || base.size()== points.size()) && (add.empty() || add.size() == v.points.size())) {
            // per-vertex attribute
            if (add.empty()) {
                base.resize(points.size(), {});
            }
            else {
                base.resize(num_points_old);
                base.insert(base.end(), add.begin(), add.end());
            }
        }
...
    };
```

**Comment by sindharta** [comment]
What is the actual problem that you are having ?

**Comment by Puppy-M** [comment]
`meshA` has normal info. Then do `meshA.mergeMesh(meshB);` , the normal info of `meshB` didn't merged into `meshA`.

**Comment by sindharta** [comment]
I mean, without looking at the code, do you have a sample DCC tool file that shows your problem ?
Any screenshot ?

**Comment by Puppy-M** [comment]
No screeshot yet. I'm right tring to implent an plugin for SketchUp base on the MeshSyncClient. And when I try to use this merge function, I noticed this issue.

**Comment by sindharta** [comment]
After a bit of investigation, it turns out that  `Mesh::mergeMesh` is a function that we are not using at all, so we are going to remove it.

**Comment by sindharta-tanuwijaya** [comment]
We removed the code in this PR, and this will be reflected in our next release.
https://github.com/unity3d-jp/MeshSync/pull/872

You are free to keep the previous code, but we are not going to maintain it.
