### ISSUE TITLE
MeshSync + Blender 2.8 RC1?

### ISSUE THREAD

**Issue by kusogaki77** [unity3d-jp/MeshSync#88]
MeshSync 2019.4.23 doesn't seem to work with Blender 2.8 RC1.

MeshSync > 使い方 > Blender > インストール　の手順でやってみました。

Preferences > Addonsに Import-Export: Unity Mesh Sync は追加されていますが、有効にしても
Toolメニューに現れません。有効にしてから保存し、Blenderを再起動してみても結果は同じです。

[ブレンダーワークスペース](https://imgur.com/a/AB4LMpk) のスクショ

エラーは全くないみたいです。

**Comment by i-saint** [comment]
thanks for the report.
I'm working on it. wait for a while.

**Comment by i-saint** [comment]
continue to #89
