### ISSUE TITLE
Blender version issue

### ISSUE THREAD

**Issue by i-saint** [unity3d-jp/MeshSync#89]
this issue treats Blender version compatibility issues.
note: **MeshSync supports only major releases of Blenders** ( https://www.blender.org/download/ ). non-major releases of Blenders ( https://builder.blender.org/download/ ) are not supported. in some cases it works, but usually not.

Blender のバージョン絡みの問題はこの issue に集約します。
前提として、**メジャーリリース以外の Blender はサポートしません**。メジャーリリースとは https://www.blender.org/download/ からダウンロードできるバージョンです。https://builder.blender.org/download/ からダウンロードできるものはメジャーリリースではなく、動作することもありますが、大抵は動作しません。

**Comment by i-saint** [comment]
the current release of MeshSync (Release 20190423) doesn't work with Blender 2.80rc. I'm working on it.

現行の MeshSync (Release 20190423) は Blender 2.80rc では機能しません。現在対応中です。

**Comment by sasa42** [comment]
Is there a way i can manually repair the workspace visibility or is this a bigger issues?

**Comment by i-saint** [comment]
you can try to build the plugin from dev branch.  there are some remaining issues, but meshes can sync.

**Comment by sasa42** [comment]
after building
\MeshSync\.MeshSync\Plugin\build_blender.bat

i get

\.MeshSync\Plugin\_out\x64_Release

/MeshSyncClientBlender-2.79
/MeshSyncClientBlender-2.80
MeshSync.lib
MeshUtils.lib

and

\.MeshSync\Plugin\_out\x64_Release\MeshSyncClientBlender-2.80
MeshSyncClientBlender.exp
MeshSyncClientBlender.lib
MeshSyncClientBlender.pdb
MeshSyncClientBlender.pyd

I did not managed to install these as Blender addon.
I tried to .zip serveral versions but had have no sucesss installing these .zips as Blender Addon.
Do you have any tip how can i pack these for the Install Add-on from File?

**Comment by i-saint** [comment]
Release 20190902 supports Blender 2.8
https://github.com/unity3d-jp/MeshSync/releases/

**Comment by Agig120** [comment]
失礼します。

動作環境 : Unity 2019.2.9f1
                  Blender 2.80

上記の環境ですとShapeKeyの反映が正しく行われないようです。
例)
1. Blenderで単一ボーンをつけただけの立方体を用意します。
2. 適当にBase以外の ShapeKey を作って変形します。(Keyの名前をKey1とします。)
3. Unity側に MeshSync します。この際 BakeModifiers はしません。
4. Unityで Key1 の変形が正しく反映されてるのを確認します。
5. Blender側に戻り、Key1 の形状を変更してUnity側に MeshSync します。
6. Unity において変更が反映されていないのが確認できます。

Blender2.79 を使用していた時は正しく反映されていたのですが、更新してから反映されなくなりました。
こちらご調査お願いできますでしょうか？
よろしくお願いいたします。
