### ISSUE TITLE
Will support blender cycles render?

### ISSUE THREAD

**Issue by Hazukiaoi** [unity3d-jp/MeshSync#9]
Hi, i like this addon and i'm a blender user.
Current released light is only support blender render?Will support cycles default emission node light?
And will support Cycles Render Principled BSDF Node?I think it maybe easy bake to standard shader.
![image](https://user-images.githubusercontent.com/5172646/40008553-27e2ed30-57d2-11e8-8bd4-39c61b1e2039.png)
Finally,I hope support NLA.NLA is a good idea, it can make animation clip easy.
NLA like this.
![image](https://user-images.githubusercontent.com/5172646/40008608-421b5f02-57d2-11e8-8fbd-044795174eb7.png)
maybe it sync like this.
![image](https://user-images.githubusercontent.com/5172646/40009516-daf0eb3c-57d4-11e8-95fb-91ba07212268.png)

I like this addon and Good luck!

**Comment by i-saint** [comment]
thanks for the valuable feedback. however, I found both of your suggestions are difficult to support. I defer it for a while. possibly I won't do it.

**Comment by sindharta** [comment]
Transferring issue to https://github.com/Unity-Technologies/MeshSyncDCCPlugin/issues/9

**Comment by sasa42** [comment]
I am working on a Blender Nodegraph based on the Principled who completly clones the HDRP Lit Shader. When you are interessted i could forward it when finished.

**Comment by sindharta** [comment]
Absolutely. Please do.

**Comment by joshuafhiggins** [comment]
> I am working on a Blender Nodegraph based on the Principled who completly clones the HDRP Lit Shader. When you are interessted i could forward it when finished.

I know you posted this a long time ago, but could you also link me to the shader?
