### ISSUE TITLE
Create Material option makes the Material Standard.

### ISSUE THREAD

**Issue by audtn5742** [unity3d-jp/MeshSync#902]
Hello
Confirmed in Blender 3.2 version Meshsync version 0.17.0.
In the Meshsync option, syncing in the Create Material state changes all the materials that were synchronized to Standard.
I tried to turn off the Create Material option and do it, but if that happens, I can't load the new material I'm working on in the blender, so I have to turn it on and do it.
This is a very serious problem because information worked on other shaders is lost.
If it was added as a feature, is there a related tutorial?

![20230327_225919](https://user-images.githubusercontent.com/46348167/227961420-12cd27cf-bda3-4da4-8822-661343666e1d.png)

**Comment by sindharta-tanuwijaya** [comment]
Thank you for the report. 

Can you please:
1. attach a sample Blender file for this ?
2. attach a video or screenshot showing the problem that you are having

**Comment by Radivarig** [comment]
Also in Unity any materials assigned to MeshSyncServer materials get destroyed and converted into default Lit, like when starting/stopping the server or ticking checkboxes in Blender.

**Comment by sindharta-tanuwijaya** [comment]
The above fix has been released in `com.unity.meshsync@0.17.2-preview`
Could you please confirm on your side if the fix solved the issue ?

**Comment by sindharta-tanuwijaya** [comment]
Closing issue due to no response.
Please don't hesitate to reach out if this issue still persists.
