### ISSUE TITLE
 Sync from multiple UV Sets (Blender Unity)

### ISSUE THREAD

**Issue by sasa42** [unity3d-jp/MeshSync#92]
Is it possible to sync at least the first 2 UV Sets available in Blender.

Example:
Blender UV0 = DetailMapUV's = Unity UV0
Blender UV1 = LightMapUV's =Unity UV1

Current Result: one UV Set gets lost, only the active one in Blender is synced.

additional information,:
Blender FBX and Collada export multiple UV Sets per default.

**Comment by sindharta** [comment]
Issue combined into the roadmap:
 https://github.com/Unity-Technologies/MeshSyncDCCPlugin/issues/6
