### ISSUE TITLE
Modeling作業時のDeform情報の更新が上書き保存できない

### ISSUE THREAD

**Issue by TsuPMC** [unity3d-jp/MeshSync#96]
お疲れ様です

今月末に大きなreleaseがあるとのことなので表題の件についても解消されるといいなぁと思いましてのご連絡です

どういう現象かと申しますと…

①　SyncしながらModeling（頂点編集）作業をした
②　mayaも保存したがUnityでもMeshSyncした①のsceneを保存した
③　Unity Projectを落とした
④　再びUnityProjectを起動
⑤　②で保存したsceneをmaya, Unity共に開き、再びSyncしながらModeling（頂点編集）した
⑥　⑤を上書き保存
⑦　再びUnity Projectを落とした
⑧　再びUnityProjectを起動
⑨　⑥のsceneを開くと②の状態のままだった

⑥の時点でsave sceneが効きません
実際には頂点編集が入っているのですが何も変更が加えられてないと認識されるようです

再保存されないと不便な理由：
編集後の見た目の確認をUnityだけで行えない
一旦mayaも起動してSyncをしないと気軽に確認できない

できれば再保存できるとより便利という内容になりますが
ご検討いただけると幸いです
（現状社内ではカスタムして上書きできるようにしましたが公式でそうなっていると尚いいなぁという希望になります）

お忙しい中恐縮ですがご検討のほどよろしくお願いいたします

動作確認：
Unity_2018.2.9f1
maya2017Update5

頂点編集であってもjointによる編集でも同じ結果でした

**Comment by i-saint** [comment]
レポートありがとうございます。
これは単純な対応漏れのようです。お手元の MeshSyncServer.cs をテキストエディタで開き、[この #endif の前](https://github.com/unity3d-jp/MeshSync/blob/master/Assets/Runtime/Scripts/MeshSyncServer.cs#L499) に以下の一行を足してもらえますでしょうか。これで意図した挙動になると思います。

`            UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEngine.SceneManagement.SceneManager.GetActiveScene());
`

**Comment by i-saint** [comment]
↑だけだと play 時にエラーが出る。改良版。

```
            if (!EditorApplication.isPlaying)
                UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEngine.SceneManagement.SceneManager.GetActiveScene());
```

**Comment by TsuPMC** [comment]
ありがとうございます
