### ISSUE TITLE
Export Quads to Unity

### ISSUE THREAD

**Issue by crogersarvr** [unity3d-jp/MeshSync#99]
My quads in maya get turned into triangles (both master and dev version).
I noticed (master maya client) a Quadify method that only gets used for unit tests.
Ive also noticed a refinement setting for quadify.

As far as I can tell, skinnedMeshRenderers only support triangles, it doesnt have a topology parameter.  It seems that the dev version doesnt support our required version, 2018.3.10.

What is my best option to get quads into unity?

At this point it seems writing/finding a quadify function in Unity is my best option.

**Comment by i-saint** [comment]
at this point, there is no way to import quads to Unity.
we have a plan to support import-time OpenSubdiv support near future (probably runtime support later),  that is why there is some code that treats quads.
we have no plan to expose quads to Unity side but maybe can add it if someone needs it. I want to know your use case.

(minimum Unity version MeshSync require won't change from 2017.4 at least in this year. dev version seems to have some problems but I will fix it)

**Comment by crogersarvr** [comment]
thanks for the details!
we need quads for realtime subdivision for oculus quest apps at facebook. arvr.
